Repository OpenRefine/OpenRefine, pull requests merged in 2021-11, with the labels that each got.

#4272 Document clone command, and Java requirements
  docs/docs/technical-reference/build-test-run.md
Labels: documentation

#4266 Fix CLI setting for memory size (-m and /m)
  refine
  refine.bat
Labels: bug, documentation

#4279 Drop support for Java 8.
  .github/workflows/pull_request.yml
  .github/workflows/snapshot_release.yml
  benchmark/pom.xml
  extensions/database/pom.xml
  extensions/gdata/pom.xml
  extensions/jython/pom.xml
  extensions/pc-axis/pom.xml
  extensions/phonetic/pom.xml
  extensions/sample/pom.xml
  extensions/wikidata/pom.xml
  packaging/pom.xml
  pom.xml
  server/pom.xml
Labels: enhancement, java version compatibility

#4275 Update contributing.md
  docs/docs/technical-reference/contributing.md
Labels: documentation

#4255 Eval error test fix
  main/src/com/google/refine/expr/functions/html/InnerHtml.java
  main/src/com/google/refine/expr/functions/html/ParseHtml.java
  main/src/com/google/refine/expr/functions/xml/ParseXml.java
  main/src/com/google/refine/expr/functions/xml/WholeText.java
  main/src/com/google/refine/expr/functions/xml/XmlText.java
  main/tests/server/src/com/google/refine/expr/EvalErrorTests.java
Labels: enhancement, grel

#4284 Warn on fill/blank down when a sorting criterion is applied
  main/tests/cypress/cypress/integration/project/grid/column/edit-cells/warning-on-blank-down.spec.js
  main/tests/cypress/cypress/integration/project/grid/column/edit-cells/warning-on-fill-down.spec.js
  main/tests/cypress/cypress/support/commands.js
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/views/data-table/data-table-view.js
  main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js
  main/webapp/modules/core/scripts/views/data-table/warn-of-pending-sort.html
Labels: enhancement, usability, UI

#4295 Fix date parsing to avoid offsets due to DST.
  main/src/com/google/refine/util/ParsingUtilities.java
Labels: bug, import, XLS(X), ODS, tests

#4297 Exclude duplicate dependency from odftoolkit.
  main/pom.xml
Labels: bug, java version compatibility

#4305 Make WbItemDocumentExpr extend EntityIdValue instead of ItemIdValue
  extensions/wikidata/src/org/openrefine/wikidata/schema/WbItemDocumentExpr.java
  extensions/wikidata/src/org/openrefine/wikidata/schema/WbStatementExpr.java
  extensions/wikidata/src/org/openrefine/wikidata/schema/WbStatementGroupExpr.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbItemDocumentExprTest.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbStatementExprTest.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbStatementGroupExprTest.java
Labels: enhancement, documentation, wikibase, wikicommons, current docs

#4315 Cleanup some unused dependencies
  main/pom.xml
  server/pom.xml
Labels: bug, maintainability, dependencies

#4280 Updated build-test-run.md no JDK later that 14.0.2
  docs/versioned_docs/version-3.4/technical-reference/build-test-run.md
Labels: documentation

#4311 4268: Add WbEntityVariable class
  extensions/wikidata/src/org/openrefine/wikidata/schema/WbEntityVariable.java
  extensions/wikidata/src/org/openrefine/wikidata/schema/WbExpression.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbEntityVariableTest.java
Labels: enhancement, wikibase, wikicommons

#4257 Move textSearchCounter to static variable
  main/tests/cypress/cypress/integration/project/grid/column/text_filter.spec.js
  main/webapp/modules/core/scripts/facets/text-search-facet.js
Labels: bug, UI

#4238 Attempt to change priority order of JRE resolution on Windows.
  packaging/pom.xml
  settings.xml
Labels: bug, java version compatibility, windows, packaging

#4292 added test for numeric facet
  main/tests/cypress/cypress/integration/project/grid/column/facet/facets.numeric.spec.js
  main/tests/cypress/cypress/support/commands.js
Labels: tests

#4309 Add ability to disable the refreshing of import previews
  extensions/database/module/langs/translation-en.json
  extensions/database/module/langs/translation-en_GB.json
  extensions/database/module/scripts/index/database-import-controller.js
  extensions/database/module/scripts/index/database-parsing-panel.html
  extensions/gdata/module/langs/translation-en.json
  extensions/gdata/module/scripts/index/gdata-parsing-panel.html
  extensions/gdata/module/scripts/index/importing-controller.js
  extensions/pc-axis/module/scripts/pc-axis-parser-ui.html
  extensions/pc-axis/module/scripts/pc-axis-parser-ui.js
  main/tests/cypress/cypress/integration/create-project/preview_project.spec.js
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.js
  main/webapp/modules/core/scripts/index/parser-interfaces/fixed-width-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/fixed-width-parser-ui.js
  main/webapp/modules/core/scripts/index/parser-interfaces/json-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/json-parser-ui.js
  main/webapp/modules/core/scripts/index/parser-interfaces/line-based-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/line-based-parser-ui.js
  main/webapp/modules/core/scripts/index/parser-interfaces/rdf-triples-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/rdf-triples-parser-ui.js
  main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.js
  main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.js
  main/webapp/modules/core/scripts/index/parser-interfaces/xml-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/xml-parser-ui.js
Labels: bug, UI, import
