Repository OpenRefine/OpenRefine, pull requests merged in 2021-01, with the labels that each got.

#3454 fix: cache all UI paths for cypress
  .github/workflows/pull_request.yml
Labels: CI/CD

#3471 Adjust the menuItem class to avoid colliding borders
  docs/src/css/custom.css
Labels: documentation

#3473 Docs > index page
  docs/docs/index.md
Labels: documentation

#3380 Docs > formatting
  docs/docs/manual/cellediting.md
  docs/docs/manual/columnediting.md
  docs/docs/manual/exploring.md
  docs/docs/manual/exporting.md
  docs/docs/manual/expressions.md
  docs/docs/manual/facets.md
  docs/docs/manual/glossary.md
  docs/docs/manual/grelfunctions.md
  docs/docs/manual/installing.md
  docs/docs/manual/key_value_columnize.md
  docs/docs/manual/reconciling.md
  docs/docs/manual/running.md
  docs/docs/manual/sortview.md
  docs/docs/manual/starting.md
  docs/docs/manual/transforming.md
  docs/docs/manual/transposing.md
  docs/docs/manual/troubleshooting.md
  docs/docs/manual/wikidata.md
  docs/sidebars.js
  docs/src/css/custom.css
  docs/static/img/export-menu.png
  docs/static/img/reconcile-with-property.png
  docs/static/img/scatterplot.png
  docs/static/img/transpose1.png
  docs/static/img/wikidata-terms.png
  docs/static/img/wikidata-terms2.png
  docs/static/img/yeardata.png
Labels: documentation

#3477 feat: move to em from pixels
  docs/src/css/custom.css
Labels: documentation

#3507 Docs > Algolia search
  docs/docusaurus.config.js
Labels: documentation

#2614 Creation of the How-To Contribute to docs
  docs/docs/technical-reference/contributing.md
Labels: documentation

#3159 Update openrefine-api.md
  docs/docs/technical-reference/openrefine-api.md
Labels: documentation

#3524 Fix links on Manual Introduction page.
  docs/docs/index.md
Labels: documentation

#3525 Improve formatting, add better links
  docs/docs/manual/troubleshooting.md
Labels: documentation

#3528 Fix broken link for technical-reference
  docs/docs/manual/troubleshooting.md
Labels: documentation

#3480 tests: UX Test for project list deletion, sort, filter
  main/tests/cypress/cypress/fixtures/fixtures.js
  main/tests/cypress/cypress/fixtures/food.mini.js
  main/tests/cypress/cypress/integration/open-project/list_projects.spec.js
  main/tests/cypress/cypress/integration/open-project/open_project.spec.js
  main/tests/cypress/cypress/integration/project/project-header/export_project.spec.js
Labels: tests

#3527 Prevent snapshot release when only docs push
  .github/workflows/snapshot_release.yml
Labels: CI/CD, documentation

#3537 fix small typo in installation docs
  docs/docs/manual/installing.md
Labels: documentation
