Repository OpenRefine/OpenRefine, pull requests merged in 2021-04, with the labels that each got.

#3795 fix: all flaky tests related to create error
  main/tests/cypress/cypress/support/commands.js
Labels: tests

#3744 Issue 3420 more facets filters
  docs/docs/technical-reference/functional-tests.md
  docs/static/img/failed-visual-test.png
  docs/static/img/visual-test-cypress-failure.png
  main/tests/cypress/.gitignore
  main/tests/cypress/cypress/integration/project/grid/column/facet/scatterplot-facet.spec.js
  main/tests/cypress/cypress/plugins/index.js
  main/tests/cypress/cypress/snapshots/project/grid/column/facet/scatterplot-facet.spec.js/scatterplot-default.snap.png
  main/tests/cypress/cypress/snapshots/project/grid/column/facet/scatterplot-facet.spec.js/scatterplot-facet-big-dot.snap.png
  main/tests/cypress/cypress/snapshots/project/grid/column/facet/scatterplot-facet.spec.js/scatterplot-facet-lin.snap.png
  main/tests/cypress/cypress/snapshots/project/grid/column/facet/scatterplot-facet.spec.js/scatterplot-facet-log.snap.png
  main/tests/cypress/cypress/snapshots/project/grid/column/facet/scatterplot-facet.spec.js/scatterplot-facet-regulat-dot.snap.png
  main/tests/cypress/cypress/snapshots/project/grid/column/facet/scatterplot-facet.spec.js/scatterplot-facet-small-dot.snap.png
  main/tests/cypress/cypress/snapshots/project/grid/column/facet/scatterplot-facet.spec.js/scatterplot-matrix-big-dot.snap.png
  main/tests/cypress/cypress/snapshots/project/grid/column/facet/scatterplot-facet.spec.js/scatterplot-matrix-lin.snap.png
  main/tests/cypress/cypress/snapshots/project/grid/column/facet/scatterplot-facet.spec.js/scatterplot-matrix-log.snap.png
  main/tests/cypress/cypress/snapshots/project/grid/column/facet/scatterplot-facet.spec.js/scatterplot-matrix-regulat-dot.snap.png
  main/tests/cypress/cypress/snapshots/project/grid/column/facet/scatterplot-facet.spec.js/scatterplot-matrix-small-dot.snap.png
  main/tests/cypress/cypress/support/commands.js
  main/tests/cypress/package.json
  main/tests/cypress/yarn.lock
Labels: documentation, tests

#3769 feat: add tests for special column All
  main/tests/cypress/cypress/integration/project/grid/all-column/.gitkeep
  main/tests/cypress/cypress/integration/project/grid/all-column/edit-columns.spec.js
  main/tests/cypress/cypress/integration/project/grid/all-column/edit-rows.spec.js
  main/tests/cypress/cypress/integration/project/grid/all-column/star.spec.js
  main/tests/cypress/cypress/integration/project/grid/all-column/view.spec.js
  main/tests/cypress/cypress/integration/project/grid/column/edit-cells/.gitkeep
  main/tests/cypress/cypress/integration/project/grid/column/edit-column/join_columns.spec.js
  main/tests/cypress/cypress/support/commands.js
Labels: UI, tests

#3814 Fixed failing test edit all column / fill down
  main/tests/cypress/cypress/integration/project/grid/all-column/edit-columns.spec.js
Labels: tests

#3722 Adding 3 prefs in the documentation: ui.browsing.pageSize, ui.browsing.facetsHistoryPanelWidth & cell-ui.previewMatchedCells
  docs/docs/manual/running.md
Labels: UI, documentation, preferences

#3459 feat: add firefox for ui_tests
  .github/workflows/snapshot_release.yml
Labels: CI/CD, tests

#3821 Remove trailing slashes in doc pages URLs to fix links.
  docs/docs/technical-reference/reconciliation-api.md
  docs/docs/technical-reference/writing-extensions.md
  docs/docusaurus.config.js
  docs/static/js/fix-location.js
Labels: documentation

#3856 Update Docusaurus to 2.0.0-alpha74
  docs/.node-version
  docs/package.json
  docs/yarn.lock
Labels: documentation

#3861 Update data-extension-api.md
  docs/docs/technical-reference/data-extension-api.md
Labels: documentation

#3860 Update suggest-api.md
  docs/docs/technical-reference/suggest-api.md
Labels: documentation

#3859 Update reconciliation-api.md
  docs/docs/technical-reference/reconciliation-api.md
Labels: documentation
