Repository OpenRefine/OpenRefine, pull requests merged in 2022-09, with the labels that each got.

#5222 Adjusted memory usage display to show the memory in use
  main/src/com/google/refine/importing/ImportingJob.java
Labels: bug

#5228 Fix skipping of fetching of existing state when uploading new files.
  extensions/wikidata/src/org/openrefine/wikidata/updates/MediaInfoEdit.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/updates/MediaInfoEditTest.java
Labels: bug, wikicommons

#5226 Revert "build(deps): bump slf4j-api from 1.7.36 to 2.0.0 (#5206)"
  pom.xml
Labels: bug, logging

#5231 Make browser list more useful
  docs/docs/manual/installing.md
  docs/docs/manual/running.md
  docs/versioned_docs/version-3.4/manual/installing.md
  docs/versioned_docs/version-3.4/manual/running.md
  docs/versioned_docs/version-3.5/manual/installing.md
  docs/versioned_docs/version-3.5/manual/running.md
  docs/versioned_docs/version-3.6/manual/installing.md
  docs/versioned_docs/version-3.6/manual/running.md
Labels: documentation, historical docs, current docs

#5239 Added and fixed labels for input fields and text areas
  main/tests/cypress/cypress/integration/project/grid/misc/expressions.spec.js
  main/webapp/modules/core/scripts/dialogs/clustering-dialog.html
  main/webapp/modules/core/scripts/dialogs/clustering-dialog.js
  main/webapp/modules/core/scripts/dialogs/expression-preview-dialog.html
  main/webapp/modules/core/scripts/index/default-importing-sources/import-from-clipboard-form.html
  main/webapp/modules/core/scripts/project/history-apply-dialog.html
  main/webapp/modules/core/scripts/project/history-panel.html
  main/webapp/modules/core/scripts/reconciliation/add-namespaced-service-dialog.html
  main/webapp/modules/core/scripts/reconciliation/add-standard-service-dialog.html
  main/webapp/modules/core/scripts/views/data-table/add-column-by-fetching-urls-dialog.html
  main/webapp/modules/core/scripts/views/data-table/add-column-dialog.html
  main/webapp/modules/core/scripts/views/data-table/add-q-column-dialog.html
Labels: accessibility

#5242 Accessibility labels cleanup II
  extensions/database/module/scripts/index/database-import-form.html
  extensions/gdata/module/scripts/index/import-from-gdata-form.html
  extensions/wikidata/module/scripts/dialogs/save-new-template-dialog.html
  main/webapp/modules/core/scripts/index/default-importing-controller/file-selection-panel.html
  main/webapp/modules/core/scripts/index/default-importing-controller/parsing-panel.html
  main/webapp/modules/core/scripts/index/import-project-ui.html
  main/webapp/modules/core/scripts/index/lang-settings-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/rdf-triples-parser-ui.html
  main/webapp/modules/core/scripts/views/data-table/copy-recon-across-columns-dialog.html
  main/webapp/modules/core/scripts/views/data-table/key-value-columnize.html
Labels: accessibility

#5256 Removed minified JavaScript for the jQuery context menu
  extensions/database/module/MOD-INF/controller.js
  extensions/database/module/scripts/index/jquery.contextMenu.js
  extensions/database/module/scripts/index/jquery.contextMenu.min.js
Labels: bug, UI, maintainability, packaging

#5235 Improve documentation about absence of support for editing sitelinks
  docs/docs/manual/wikibase/overview.md
  docs/versioned_docs/version-3.6/manual/wikibase/overview.md
Labels: documentation, historical docs, current docs

#5230 Expand documentation for Wikibases with file upload
  docs/docs/manual/wikibase/configuration.md
Labels: documentation, wikibase, current docs

#5286 Fix reconciliation dialog overflow issue.
  main/webapp/modules/core/scripts/reconciliation/standard-service-panel.html
  main/webapp/modules/core/styles/reconciliation/recon-dialog.less
Labels: bug, reconciliation, UX

#5274 Remove 'url' format in Wikibase manifest JSON schema
  extensions/wikidata/module/scripts/wikibase-manifest-schema-v1.js
  extensions/wikidata/module/scripts/wikibase-manifest-schema-v2.js
Labels: bug, wikibase

#5253 Adjusted the colors in range and timerange facet to have more contrast
  main/webapp/modules/core/scripts/facets/range-facet.js
  main/webapp/modules/core/scripts/facets/timerange-facet.js
Labels: enhancement, UI, facets, accessibility

#5290 Added a test for All column -> 'Show / Hide null values'
  main/tests/cypress/cypress/integration/project/grid/all-column/view.spec.js
  main/webapp/modules/core/langs/translation-en.json
Labels: tests

#5284 Aria labels cleanup
  extensions/wikidata/module/langs/translation-en.json
  extensions/wikidata/module/scripts/dialogs/add-wikibase-dialog.html
  extensions/wikidata/module/scripts/dialogs/wikibase-dialog.js
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/dialogs/templating-exporter-dialog.html
  main/webapp/modules/core/scripts/dialogs/templating-exporter-dialog.js
  main/webapp/modules/core/scripts/project/history-extract-dialog.html
  main/webapp/modules/core/scripts/project/history-panel.js
  main/webapp/modules/core/scripts/reconciliation/standard-service-panel.html
  main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
  main/webapp/modules/core/scripts/views/data-table/cell-editor.html
  main/webapp/modules/core/scripts/views/data-table/cell-recon-search-for-match.html
  main/webapp/modules/core/scripts/views/data-table/cell-ui.js
  main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
  main/webapp/modules/core/scripts/views/data-table/rename-column.html
  main/webapp/modules/core/scripts/views/data-table/transpose-columns-into-rows.html
Labels: accessibility

#5263 Make respondException print the exception stacktrace
  main/src/com/google/refine/commands/Command.java
Labels: error handling
