Repository OpenRefine/OpenRefine, pull requests merged in 2022-07, with the labels that each got.

#4999 Java versioning
  docs/versioned_docs/version-3.5/manual/installing.md
Labels: documentation, historical docs

#4971 #816 improve toString to work with numbers
  main/src/com/google/refine/expr/functions/ToString.java
  main/tests/server/src/com/google/refine/expr/functions/ToStringTests.java
Labels: enhancement, logic, grel

#4900 Deleted the first default Sheet in OdsExporter
  main/src/com/google/refine/exporters/OdsExporter.java
  main/tests/server/src/com/google/refine/exporters/OdsExporterTests.java
Labels: bug, export, ODS

#5021 Update release process in technical docs
  docs/docs/technical-reference/version-release-process.md
Labels: documentation, current docs

#4992 Added fix to fit longer descriptions of suggest properties
  main/webapp/modules/core/MOD-INF/controller.js
  main/webapp/modules/core/externals/suggest/css/suggest-4_3.css
  main/webapp/modules/core/externals/suggest/css/suggest-4_3.min.css
Labels: bug, UI, wikibase

#5030 Added 'Discover Wikibase instances…' button to the 'Select Wikibase instance' dialog.
  extensions/wikidata/module/langs/translation-en.json
  extensions/wikidata/module/scripts/dialogs/wikibase-dialog.html
  extensions/wikidata/module/scripts/dialogs/wikibase-dialog.js
Labels: enhancement, wikibase

#5028 Add support for editing wikitext associated to MediaInfo entities
  extensions/wikidata/module/langs/translation-en.json
  extensions/wikidata/module/scripts/previewrenderer.js
  extensions/wikidata/module/scripts/schema-alignment.js
  extensions/wikidata/module/styles/schema-alignment.less
  extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java
  extensions/wikidata/src/org/openrefine/wikidata/editing/MediaFileUtils.java
  extensions/wikidata/src/org/openrefine/wikidata/editing/ReconEntityRewriter.java
  extensions/wikidata/src/org/openrefine/wikidata/schema/WbMediaInfoEditExpr.java
  extensions/wikidata/src/org/openrefine/wikidata/updates/FullMediaInfoUpdate.java
  extensions/wikidata/src/org/openrefine/wikidata/updates/MediaInfoEdit.java
  extensions/wikidata/src/org/openrefine/wikidata/updates/MediaInfoEditBuilder.java
  extensions/wikidata/src/org/openrefine/wikidata/updates/scheduler/WikibaseAPIUpdateScheduler.java
  extensions/wikidata/tests/data/schema/with_mediainfo.json
  extensions/wikidata/tests/data/updates/mediainfo_update.json
  extensions/wikidata/tests/src/org/openrefine/wikidata/editing/EditBatchProcessorTest.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/editing/MediaFileUtilsTest.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbMediaInfoEditExprTest.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/updates/MediaInfoEditTest.java
Labels: enhancement, wikicommons

#5090 Fixed sample extension pom
  extensions/sample/pom.xml
Labels: bug

#5031 Purge wikitext after making edits to MediaInfo entities
  extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java
  extensions/wikidata/src/org/openrefine/wikidata/editing/MediaFileUtils.java
  extensions/wikidata/src/org/openrefine/wikidata/updates/MediaInfoEdit.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/editing/MediaFileUtilsTest.java
Labels: enhancement, wikicommons

#5042 Enable locating rows generating certain Wikibase issues with facets.
  extensions/wikidata/module/MOD-INF/controller.js
  extensions/wikidata/module/langs/translation-en.json
  extensions/wikidata/module/scripts/warningsrenderer.js
  extensions/wikidata/src/org/openrefine/wikidata/functions/WikibaseIssuesFunction.java
  extensions/wikidata/src/org/openrefine/wikidata/manifests/ManifestParser.java
  extensions/wikidata/src/org/openrefine/wikidata/qa/QAWarning.java
  extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/ConflictsWithScrutinizer.java
  extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/DistinctValuesScrutinizer.java
  extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/EditScrutinizer.java
  extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/InverseConstraintScrutinizer.java
  extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/NoEditsMadeScrutinizer.java
  extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/SingleValueScrutinizer.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/functions/WikibaseIssuesFunctionTests.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/qa/QAWarningStoreTest.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/qa/QAWarningTest.java
  main/src/com/google/refine/expr/EvalError.java
  main/webapp/modules/core/scripts/facets/list-facet.js
Labels: enhancement, UI, facets, wikibase

#5049 Improved Wikibase selection UI
  extensions/wikidata/module/langs/translation-en.json
  extensions/wikidata/module/scripts/dialogs/wikibase-dialog.html
  extensions/wikidata/module/scripts/dialogs/wikibase-dialog.js
  extensions/wikidata/module/scripts/dialogs/wikibase-item.html
  extensions/wikidata/module/scripts/menu-bar-extension.js
  extensions/wikidata/module/styles/dialogs/wikibase-dialog.less
Labels: enhancement, UI, wikibase, UX

#5091 Fix preview of MediaInfo entities
  extensions/wikidata/module/styles/schema-alignment.less
Labels: bug, wikicommons

#5109 Added fix so the gdata importer gets the date properly
  extensions/gdata/module/scripts/index/gdata-source-ui.js
  main/webapp/modules/core/scripts/util/misc.js
Labels: bug, import, google

#4987 547 handle gzip compressed files without gz extension
  main/src/com/google/refine/importing/ImportingUtilities.java
  main/tests/data/persons
  main/tests/data/persons.csv.gz
  main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java
Labels: bug, priority: Medium, import

#5045 2443 set the locale based on userLang from preferences
  main/src/com/google/refine/commands/SetPreferenceCommand.java
  main/src/com/google/refine/io/FileProjectManager.java
  main/src/com/google/refine/util/LocaleUtils.java
Labels: documentation

#5108 remove ignorewarnings=0
  extensions/wikidata/src/org/openrefine/wikidata/editing/MediaFileUtils.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/editing/MediaFileUtilsTest.java
Labels: enhancement, wikicommons

#5128 [doc] docusaurus installation
  docs/docs/technical-reference/contributing.md
  docs/versioned_docs/version-3.6/technical-reference/contributing.md
Labels: bug, documentation, historical docs, current docs
