Repository OpenRefine/OpenRefine, pull requests merged in 2022-06, with the labels that each got.

#4752 (I#2606) Add 2 new grel functions for replacing strings matching a search list
  docs/docs/manual/grelfunctions.md
  main/src/com/google/refine/expr/functions/strings/ReplaceEach.java
  main/src/com/google/refine/grel/ControlFunctionRegistry.java
  main/tests/server/src/com/google/refine/expr/functions/strings/ReplaceEachTest.java
Labels: enhancement, documentation, grel, current docs

#4916 Updates Jetty to avoid potential security risks
  pom.xml
Labels: security

#4921 #4889 Remove distclean option
  refine
  refine.bat
Labels: bug

#4919 Restrict protocols available at project creation
  main/src/com/google/refine/importing/ImportingUtilities.java
  main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java
Labels: import, fetch urls, vulnerability

#4917 Revert back to previous behaviour for insertion of ids in URL templates for reconciliation
  main/webapp/modules/core/scripts/views/data-table/cell-ui.js
Labels: bug, reconciliation, reconciliation API design

#4863 Initial support for file upload in Wikibase extension
  extensions/wikidata/module/langs/translation-en.json
  extensions/wikidata/module/scripts/previewrenderer.js
  extensions/wikidata/module/scripts/schema-alignment.js
  extensions/wikidata/module/styles/schema-alignment.less
  extensions/wikidata/src/org/openrefine/wikidata/commands/ConnectionManager.java
  extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java
  extensions/wikidata/src/org/openrefine/wikidata/editing/MediaFileUtils.java
  extensions/wikidata/src/org/openrefine/wikidata/editing/ReconEntityRewriter.java
  extensions/wikidata/src/org/openrefine/wikidata/operations/PerformWikibaseEditsOperation.java
  extensions/wikidata/src/org/openrefine/wikidata/qa/scrutinizers/NewEntityScrutinizer.java
  extensions/wikidata/src/org/openrefine/wikidata/schema/WbItemEditExpr.java
  extensions/wikidata/src/org/openrefine/wikidata/schema/WbMediaInfoEditExpr.java
  extensions/wikidata/src/org/openrefine/wikidata/updates/FullMediaInfoUpdate.java
  extensions/wikidata/src/org/openrefine/wikidata/updates/MediaInfoEdit.java
  extensions/wikidata/src/org/openrefine/wikidata/updates/MediaInfoEditBuilder.java
  extensions/wikidata/src/org/openrefine/wikidata/updates/scheduler/WikibaseAPIUpdateScheduler.java
  extensions/wikidata/tests/data/schema/with_mediainfo.json
  extensions/wikidata/tests/data/updates/mediainfo_update.json
  extensions/wikidata/tests/src/org/openrefine/wikidata/editing/EditBatchProcessorTest.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/editing/MediaFileUtilsTest.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/qa/scrutinizers/NewEntityScrutinizerTest.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/schema/WbMediaInfoEditExprTest.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/updates/MediaInfoEditTest.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/updates/scheduler/UpdateSchedulerTest.java
Labels: enhancement, export, wikicommons

#4940 Added fix for Wikibase login buttons
  extensions/wikidata/module/scripts/dialogs/manage-account-dialog.js
Labels: bug, wikibase

#4941 Improved error message for invalid manifest version
  extensions/wikidata/module/langs/translation-en.json
  extensions/wikidata/module/scripts/dialogs/wikibase-dialog.js
Labels: enhancement, error handling, wikibase

#4942 Remove references to specific versions of OpenRefine in the docs.
  docs/docs/index.md
  docs/docs/manual/installing.md
  docs/versioned_docs/version-3.5/index.md
  docs/versioned_docs/version-3.5/manual/installing.md
Labels: documentation, historical docs, current docs

#4954 4546 invalid url detection in cell UI
  main/webapp/modules/core/scripts/views/data-table/cell-ui.js
Labels: bug, UI

#4949 Updated refine.bat to use %JAVA_HOME% and be consistent with the refine script
  refine
  refine.bat
Labels: bug, java version compatibility

#4961 Updated GitHub PR workflow to ignore langs
  .github/workflows/pull_request.yml
Labels: bug, tests

#4893 Added error messages for scatterplot facet
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/views/data-table/menu-facets.js
Labels: bug, facets, error handling

#4898 Added whitespaces to the "collapse consecutive whitespaces" command
  main/tests/cypress/cypress/integration/project/grid/column/edit-cells/common-transforms/collapse-consecutive-whitespace.spec.js
  main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js
Labels: bug

#4963 add mention of "transliteration" in our fingerprint() function
  docs/versioned_docs/version-3.5/manual/grelfunctions.md
Labels: documentation, historical docs

#4997 Cleaning up and removing old freebase methods and references
  main/src/com/google/refine/importers/OdsImporter.java
  main/tests/server/src/com/google/refine/importers/RdfTripleImporterTests.java
  main/webapp/modules/core/about.html
Labels: maintainability, freebase cleanup
