Repository OpenRefine/OpenRefine, pull requests merged in 2022-03, with the labels that each got.

#4578 Right align buttons
  extensions/wikidata/module/scripts/dialogs/add-wikibase-dialog.html
  extensions/wikidata/module/scripts/dialogs/import-schema-dialog.html
  extensions/wikidata/module/scripts/dialogs/wikibase-dialog.html
  extensions/wikidata/module/styles/dialogs/add-wikibase-dialog.less
  extensions/wikidata/module/styles/dialogs/manage-account-dialog.less
  extensions/wikidata/module/styles/dialogs/wikibase-dialog.less
  main/webapp/modules/core/scripts/dialogs/common-transform-dialog.html
  main/webapp/modules/core/scripts/dialogs/custom-tabular-exporter-dialog.html
  main/webapp/modules/core/scripts/dialogs/export-project-dialog.html
  main/webapp/modules/core/scripts/dialogs/sql-exporter-dialog.html
  main/webapp/modules/core/styles/util/dialog.less
Labels: bug, usability, UI

#4571 Increase form max content size
  server/src/com/google/refine/Refine.java
Labels: bug

#4573 Add tag and edit speed parameters in Wikibase manifest
  docs/docs/manual/wikibase/configuration.md
  extensions/wikidata/module/scripts/dialogs/perform-edits-dialog.js
  extensions/wikidata/module/scripts/wikibase-manager.js
  extensions/wikidata/module/scripts/wikibase-manifest-schema-v1.js
  extensions/wikidata/module/scripts/wikibase-manifest-schema-v2.js
  extensions/wikidata/src/org/openrefine/wikidata/commands/PerformWikibaseEditsCommand.java
  extensions/wikidata/src/org/openrefine/wikidata/editing/EditBatchProcessor.java
  extensions/wikidata/src/org/openrefine/wikidata/manifests/Manifest.java
  extensions/wikidata/src/org/openrefine/wikidata/manifests/ManifestV1.java
  extensions/wikidata/src/org/openrefine/wikidata/manifests/ManifestV2.java
  extensions/wikidata/src/org/openrefine/wikidata/operations/PerformWikibaseEditsOperation.java
  extensions/wikidata/tests/data/operations/perform-edits.json
  extensions/wikidata/tests/src/org/openrefine/wikidata/editing/EditBatchProcessorTest.java
  extensions/wikidata/tests/src/org/openrefine/wikidata/operations/PerformWikibaseEditsOperationTest.java
Labels: bug, documentation, wikibase, current docs

#4586 SQL exporter width
  main/webapp/modules/core/scripts/dialogs/sql-exporter-dialog.html
Labels: bug, UI

#4597 Rename column popup
  main/tests/cypress/cypress/integration/project/grid/column/edit-column/rename_remove_column.spec.js
  main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
  main/webapp/modules/core/scripts/views/data-table/rename-column.html
Labels: bug, usability, UI

#4604 Update memory allocation steps for Mac
  docs/docs/manual/installing.md
  docs/versioned_docs/version-3.5/manual/installing.md
Labels: documentation, historical docs, current docs

#4605 Validation of all URLs in URL import
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/index/default-importing-controller/controller.js
  main/webapp/modules/core/scripts/index/default-importing-sources/sources.js
Labels: bug, import

#4613 Edit project tags tooltip
  main/webapp/modules/core/scripts/index/open-project-ui.js
  main/webapp/modules/core/styles/index/open-project-ui.less
Labels: bug, UI

#4618 Frontend dependency management
  .gitignore
  main/webapp/package.json
Labels: enhancement, maintainability

#4623 Spacing between ok/cancel buttons for custom text/numeric facet dialogs
  main/webapp/modules/core/styles/util/dialog.less
Labels: bug, UI

#4601 Set more restrictive file permissions on workspace.json
  main/src/com/google/refine/io/FileProjectManager.java
Labels: enhancement, security

#4594 Update Wikidata-Toolkit to 0.13.1
  extensions/wikidata/pom.xml
Labels: bug, enhancement, wikibase, dependencies, wikicommons

#4636 disable spellcheck on input text type
  extensions/database/module/scripts/index/database-import-form.html
  extensions/database/module/scripts/index/database-parsing-panel.html
  extensions/gdata/module/scripts/index/gdata-parsing-panel.html
  extensions/pc-axis/module/scripts/pc-axis-parser-ui.html
  main/webapp/modules/core/scripts/dialogs/clustering-dialog.html
  main/webapp/modules/core/scripts/dialogs/custom-tabular-exporter-dialog.html
  main/webapp/modules/core/scripts/dialogs/sql-exporter-dialog.html
  main/webapp/modules/core/scripts/dialogs/templating-exporter-dialog.html
  main/webapp/modules/core/scripts/index/default-importing-controller/file-selection-panel.html
  main/webapp/modules/core/scripts/index/default-importing-sources/import-from-clipboard-form.html
  main/webapp/modules/core/scripts/index/import-project-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/fixed-width-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/json-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/line-based-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.html
  main/webapp/modules/core/scripts/project/history-apply-dialog.html
  main/webapp/modules/core/scripts/project/history-extract-dialog.html
  main/webapp/modules/core/scripts/project/history-panel.html
  main/webapp/modules/core/scripts/views/data-table/replace-dialog.html
Labels: enhancement, UI

#4642 modify default return of call() for ToString to state for…
  main/src/com/google/refine/expr/functions/ToString.java
Labels: error handling

#4635 Redirect to wiki for Google Export options
  extensions/gdata/src/com/google/refine/extension/gdata/GoogleAPIExtension.java
Labels: bug, google

#4657 fix typo in "reconciliation"
  docs/docs/manual/reconciling.md
  docs/versioned_docs/version-3.5/manual/reconciling.md
Labels: documentation, historical docs, current docs

#4630 Wikibase dialog buttons
  extensions/wikidata/module/scripts/dialogs/logged-in-dialog.html
  extensions/wikidata/module/scripts/dialogs/owner-only-consumer-login-dialog.html
  extensions/wikidata/module/scripts/dialogs/password-login-dialog.html
  extensions/wikidata/module/styles/dialogs/manage-account-dialog.less
Labels: bug, UI

#4641 fixes #4640 added example of Regex usage to desc of replace()
  main/src/com/google/refine/expr/functions/strings/Replace.java
Labels: grel, current docs

#4653 fixes OpenRefine#4644 update Maven version to 3.8.5
  refine
Labels: bug, maven

#4668 Removed 4px dialog border and added missing header
  main/webapp/modules/core/langs/translation-ceb.json
  main/webapp/modules/core/langs/translation-de.json
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/langs/translation-es.json
  main/webapp/modules/core/langs/translation-fil.json
  main/webapp/modules/core/langs/translation-fr.json
  main/webapp/modules/core/langs/translation-he.json
  main/webapp/modules/core/langs/translation-hu.json
  main/webapp/modules/core/langs/translation-it.json
  main/webapp/modules/core/langs/translation-jp.json
  main/webapp/modules/core/langs/translation-nl.json
  main/webapp/modules/core/langs/translation-pt.json
  main/webapp/modules/core/langs/translation-pt_BR.json
  main/webapp/modules/core/langs/translation-ru.json
  main/webapp/modules/core/langs/translation-tl.json
  main/webapp/modules/core/langs/translation-zh.json
  main/webapp/modules/core/scripts/views/data-table/data-table-view.js
  main/webapp/modules/core/styles/util/dialog.less
Labels: bug, UI
