Repository OpenRefine/OpenRefine, pull requests merged in 2023-04, with the labels that each got.

#5771 Style the input type=file button as other buttons #5743
  main/webapp/modules/core/MOD-INF/controller.js
  main/webapp/modules/core/styles/common.css
  main/webapp/modules/core/styles/pure.css
Labels: enhancement, UI

#5676 5449-add-item-button
  extensions/wikibase/module/scripts/schema-alignment-tab.html
  extensions/wikibase/module/styles/schema-alignment.css
Labels: UI, wikibase, wikicommons, UX

#5767 Fix initial facet height when facets are added while the facet panel is not visible
  main/webapp/modules/core/scripts/facets/list-facet.js
  main/webapp/modules/core/scripts/project/browsing-engine.js
Labels: bug, UI, facets

#5777 Added fix for command line options in refine
  refine
  refine.bat
Labels: bug

#5775 Fixed project metadata dialog so it doesn't jump to the top left corner when it is dragged
  main/webapp/modules/core/scripts/index/edit-metadata-dialog.js
Labels: bug

#5787 Closes #4625. Manages importing URL with illegal characters
  main/src/com/google/refine/importing/ImportingUtilities.java
  main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java
Labels: bug, import, windows

#5674 Issue #5388 fix case in sql column names
  main/src/com/google/refine/exporters/sql/SqlCreateBuilder.java
  main/src/com/google/refine/exporters/sql/SqlInsertBuilder.java
Labels: bug, export, SQL/database

#5798 Removed the support log in refine.bat and added a "free memory" banner to refine.bat
  refine.bat
Labels: bug

#5801 Optimize project deletion after Cypress tests
  main/tests/cypress/cypress/support/openrefine_api.js
Labels: bug, tests

#5809 Fix usage of MediaWiki API in auto-completion for fields in the Wikibase schema
  extensions/wikibase/module/scripts/wikibase-suggest.js
Labels: bug, localization, wikibase

#4897 (I#3805) Fix problem with frequent writes to metadata files
  main/src/com/google/refine/ProjectMetadata.java
  main/src/com/google/refine/io/FileProjectManager.java
  main/src/com/google/refine/io/ProjectMetadataUtilities.java
  main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java
Labels: bug

#5804 Flush precompute cache on revert of RowRemovalOperation
  main/src/com/google/refine/model/changes/MassRowChange.java
  main/src/com/google/refine/model/changes/RowRemovalChange.java
  main/tests/server/src/com/google/refine/model/CacheTests.java
  main/tests/server/src/com/google/refine/operations/row/RowRemovalOperationTests.java
Labels: bug, facets

#5817 Updated the names of the CI tests and updated refine
  .github/workflows/pull_request.yml
  .github/workflows/snapshot_release.yml
  main/tests/cypress/build-test-matrix.js
  refine
Labels: bug

#5816 Invoke Maven in batch mode in CI to avoid progress info in logs
  .github/workflows/pull_request.yml
  .github/workflows/snapshot_release.yml
Labels: CI/CD

#5815 Reformat Eclipse config file
  server/IDEs/eclipse/Refine with extensions.launch
Labels: maintainability
