Repository OpenRefine/OpenRefine, pull requests merged in 2023-12, with the labels that each got.

#6198 Made text selectable in alert dialog
  extensions/gdata/module/authorized.vt
  extensions/gdata/module/langs/translation-en.json
  extensions/gdata/module/scripts/index/gdata-source-ui.js
  extensions/gdata/module/scripts/index/importing-controller.js
  extensions/gdata/module/scripts/project/exporters.js
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/util/dialog.js
Labels: Type: Bug, Theme: UX/Usability, error handling

#6227 Widen regex of allowed characters in Commons filenames.
  extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizer.java
  extensions/wikibase/tests/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizerTest.java
Labels: Type: Bug, wikibase, wikicommons

#6229 Add 'lint' option to refine(.bat) scripts
  refine
  refine.bat
Labels: Type: Feature Request, maintainability

#6226 Fixed Maven tests to work in different locales
  main/tests/server/src/com/google/refine/importers/ExcelImporterTests.java
  main/tests/server/src/com/google/refine/importers/ImporterUtilitiesTests.java
  main/tests/server/src/com/google/refine/importers/SeparatorBasedImporterTests.java
  main/tests/server/src/com/google/refine/operations/recon/ReconOperationTests.java
Labels: Type: Bug, tests

#6239 Make UI update when matching cell
  main/webapp/modules/core/scripts/views/data-table/cell-renderers/recon-renderer.js
Labels: Type: Bug, reconciliation

#6242 Make sure encoding is set before fetching writer. Fixes #6063
  main/src/com/google/refine/commands/Command.java
Labels: Type: Bug, encoding, reconciliation

#6192 Adds the Search for match option
  main/webapp/modules/core/scripts/views/data-table/cell-renderers/recon-renderer.js
  main/webapp/modules/core/styles/views/data-table-view.css
Labels: Type: Bug, reconciliation, error handling

#6191 Improve error messages in reconciliation operation#6111
  main/src/com/google/refine/model/recon/StandardReconConfig.java
  main/src/com/google/refine/operations/recon/ReconOperation.java
  main/tests/server/src/com/google/refine/model/recon/StandardReconConfigTests.java
Labels: Type: Feature Request, reconciliation, error handling

#6260 Qualify selectors with metadata dialog ID. Fixes #6259
  main/tests/cypress/cypress/e2e/project/grid/column/facet/facets.cy.js
  main/tests/cypress/cypress/e2e/project_management/project_metadata.cy.js
Labels: Type: Bug, tests
