Repository OpenRefine/OpenRefine, pull requests merged in 2023-11, with the labels that each got.

#6141 Return error, not null, on bad URL. Fixes #6137.
  main/src/com/google/refine/util/HttpClient.java
  main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java
Labels: Type: Bug, fetch urls, error handling

#6130 Fix bzip2 import and add support for concatenated compressed streams
  main/src/com/google/refine/importers/TextFormatGuesser.java
  main/src/com/google/refine/importing/ImportingUtilities.java
  main/tests/data/persons.csv
  main/tests/data/persons.csv.bz2
  main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java
Labels: Type: Bug, import

#6157 Replace custom formatRelativeDate with standard Intl.RelativeTimeFormat.format()
  main/webapp/modules/core/langs/translation-ceb.json
  main/webapp/modules/core/langs/translation-cs.json
  main/webapp/modules/core/langs/translation-de.json
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/langs/translation-es.json
  main/webapp/modules/core/langs/translation-fil.json
  main/webapp/modules/core/langs/translation-fr.json
  main/webapp/modules/core/langs/translation-he.json
  main/webapp/modules/core/langs/translation-hu.json
  main/webapp/modules/core/langs/translation-id.json
  main/webapp/modules/core/langs/translation-it.json
  main/webapp/modules/core/langs/translation-ja.json
  main/webapp/modules/core/langs/translation-nb_NO.json
  main/webapp/modules/core/langs/translation-nl.json
  main/webapp/modules/core/langs/translation-pl.json
  main/webapp/modules/core/langs/translation-pt.json
  main/webapp/modules/core/langs/translation-pt_BR.json
  main/webapp/modules/core/langs/translation-ru.json
  main/webapp/modules/core/langs/translation-sv.json
  main/webapp/modules/core/langs/translation-tl.json
  main/webapp/modules/core/langs/translation-zh.json
  main/webapp/modules/core/scripts/util/misc.js
Labels: Type: Bug, Priority: Low, Module: Frontend

#6162 Fix flaky Cypress test in cypress/e2e/create-project/preview_project.cy.js "Tests disabling of automatic preview"
  main/tests/cypress/cypress/e2e/create-project/preview_project.cy.js
  main/tests/cypress/cypress/support/commands.js
Labels: Type: Bug, tests

#6151 Add missing space in "add column based on reconciled values" dialog
  main/webapp/modules/core/scripts/dialogs/add-column-by-reconciliation.js
Labels: Type: Bug, Module: Frontend, Good First Issue

#6175 Defer initialization of Jython interpeter from startup. Fixes #6174
  extensions/jython/src/com/google/refine/jython/JythonEvaluable.java
Labels: Type: Feature Request

#6180 Fix flaky tests
  main/tests/server/src/com/google/refine/browsing/facets/ListFacetTests.java
Labels: Type: Bug

#6176 Switch HistoryEntry to Instant from OffsetDateTime(at UTC)
  main/src/com/google/refine/history/HistoryEntry.java
Labels: Type: Bug, Priority: Medium, persistence, metadata

#6190 Update Velocity from 1.5 to 2.3. Fixes #4078 / CVE-2020-13936
  main/pom.xml
  main/webapp/WEB-INF/velocity.properties
  pom.xml
Labels: vulnerability

#6161 Fix DeleteProject NPE during e2e tests. Fixes #3479.
  main/src/com/google/refine/ProjectManager.java
  main/src/com/google/refine/commands/project/DeleteProjectCommand.java
  main/src/com/google/refine/commands/project/RenameProjectCommand.java
  main/src/com/google/refine/commands/project/SetProjectMetadataCommand.java
  main/src/com/google/refine/commands/project/SetProjectTagsCommand.java
  main/src/com/google/refine/commands/workspace/GetAllProjectTagsCommand.java
  main/src/com/google/refine/io/FileProjectManager.java
  main/tests/server/src/com/google/refine/ProjectManagerTests.java
  main/tests/server/src/com/google/refine/commands/CommandTestBase.java
  main/tests/server/src/com/google/refine/commands/project/RenameProjectCommandTests.java
  main/tests/server/src/com/google/refine/commands/project/SetProjectMetadataCommandTests.java
  main/tests/server/src/com/google/refine/commands/project/SetProjectTagsCommandTests.java
  main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java
Labels: Type: Bug, Module: Frontend, tests, Module: Backend

#6173 Localize date on Open Project page. Fixes #6172
  main/webapp/modules/core/scripts/index/open-project-ui.js
  main/webapp/modules/core/scripts/util/i18n.js
  main/webapp/modules/core/styles/index/open-project-ui.css
Labels: Type: Feature Request, Priority: Low
