Repository OpenRefine/OpenRefine, pull requests merged in 2023-03, with the labels that each got.

#5588 Filter empty tokens to match doc. Fixes #5587
  main/src/com/google/refine/expr/functions/strings/Split.java
  main/tests/server/src/com/google/refine/expr/functions/strings/SplitTests.java
Labels: bug, grel

#5660 Updated build test matrix to use GitHub environment files
  main/tests/cypress/build-test-matrix.js
Labels: CI/CD, github_actions

#5650 Fix a bug of object array convertion and adjust error message
  main/src/com/google/refine/expr/functions/strings/ReplaceEach.java
  main/tests/server/src/com/google/refine/expr/functions/strings/ReplaceEachTest.java
Labels: bug, documentation, grel

#5662 Fixed regression that prevents UI tests from running in CI
  .github/workflows/pull_request.yml
  main/tests/cypress/build-test-matrix.js
Labels: CI/CD, github_actions

#5673 Refine bat consistency cleanup
  refine.bat
Labels: bug, priority: High, documentation, windows

#5689 updated the error code
  refine
Labels: bug

#5550 database extension: drop Bootstrap and Pure #5548
  extensions/database/module/MOD-INF/controller.js
  extensions/database/module/scripts/database-extension.js
  extensions/database/module/scripts/index/database-import-form.html
  extensions/database/module/scripts/index/database-source-ui.js
  extensions/database/module/styles/bootstrap.css
  extensions/database/module/styles/database-import.css
  extensions/database/module/styles/pure.css
Labels: bug, UI, maintainability, extension

#5711 Added fix for command line options in refine.bat
  refine.bat
Labels: bug, priority: High, windows

#5720 update refine script to fail on mvn compile failure
  refine
Labels: bug, error handling

#5722 Waiting screen while guessing reconciliation types should be internal to the reconciliation dialog #4877
  main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
Labels: enhancement, UI, reconciliation

#5713 Updated cross function
  main/src/com/google/refine/LookupCacheManager.java
  main/tests/server/src/com/google/refine/expr/functions/CrossTests.java
Labels: bug, grel

#5724 Made it so dialogs cannot be dragged past the top of the window
  main/webapp/modules/core/scripts/util/dialog.js
Labels: bug, UI

#5742 Fix style of project creation progress bar.
  main/webapp/modules/core/styles/index/create-project-ui.css
Labels: bug, UI

#5733 gives preference to user if they want to automatch or not
  main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
Labels: enhancement, reconciliation, preferences

#5758 Fix locale loading in the frontend
  main/webapp/modules/core/scripts/util/i18n.js
Labels: bug, localization
