Repository OpenRefine/OpenRefine, pull requests merged in 2023-02, with the labels that each got.

#5608 Added a fix to keep the facet height after performing various operations
  main/webapp/modules/core/scripts/facets/list-facet.js
Labels: bug, UI, facets

#5611 Added a fix to stop the facets panel from shifting on refresh
  main/webapp/modules/core/scripts/project/browsing-engine.js
  main/webapp/modules/core/styles/project/sidebar.css
Labels: bug, UI, facets

#5551 Use internationalized word separator. Fixes #557.
  main/webapp/modules/core/scripts/views/data-table/menu-facets.js
Labels: bug, priority: Medium, facets

#5477 Handle proxy configuration, closes #5476
  conf/openrefine.l4j.ini
  main/src/com/google/refine/util/HttpClient.java
  main/tests/server/src/com/google/refine/util/HttpClientTests.java
Labels: bug

#5621 Fixes #5620 adds "bytes" to end of logger string
  server/src/com/google/refine/Refine.java
Labels: enhancement, logging

#5612 Add workflow to unassign contributors from good first issues after a delay
  .github/workflows/unassign_issues.yml
Labels: maintainability

#5632 Fix for failing Cypress CI test
  main/tests/cypress/cypress/e2e/project/grid/column/reconcile/actions/create_new_item_for_each.cy.js
Labels: bug, maintainability, CI/CD

#5629 Enhance forRange to accept negative increments (#5520)
  main/src/com/google/refine/grel/controls/ForRange.java
  main/tests/server/src/com/google/refine/grel/controls/ForRangeTests.java
Labels: enhancement, grel

#5644 Removed unneeded commands and lines in the Linux refine script
  refine
Labels: enhancement

#5646 Updated Maven in refine script
  refine
  refine.bat
Labels: bug, maven

#5634 Fix accessor for "record" field in lists of WrappedRows (output by cross function)
  main/src/com/google/refine/expr/WrappedRow.java
  main/src/com/google/refine/expr/functions/Cross.java
  main/tests/server/src/com/google/refine/expr/functions/CrossTests.java
Labels: bug, grel
