Repository OpenRefine/OpenRefine, pull requests merged in 2024-12, with the labels that each got.

#6907 apply-operations: Report invalid JSON structure from the backend to the frontend
  main/src/com/google/refine/commands/history/ApplyOperationsCommand.java
  main/tests/server/src/com/google/refine/commands/history/ApplyOperationsCommandTests.java
  main/webapp/modules/core/scripts/project/history-panel.js
  main/webapp/modules/core/styles/project/sidebar.css
Labels: size/S

#6967 Allow uploading new file versions
  extensions/wikibase/module/langs/translation-en.json
  extensions/wikibase/src/org/openrefine/wikibase/editing/EditBatchProcessor.java
  extensions/wikibase/src/org/openrefine/wikibase/editing/MediaFileUtils.java
  extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizer.java
  extensions/wikibase/src/org/openrefine/wikibase/updates/MediaInfoEdit.java
  extensions/wikibase/tests/src/org/openrefine/wikibase/editing/EditBatchProcessorTest.java
  extensions/wikibase/tests/src/org/openrefine/wikibase/editing/MediaFileUtilsTest.java
  extensions/wikibase/tests/src/org/openrefine/wikibase/qa/scrutinizers/FileNameScrutinizerTest.java
Labels: Type: Feature Request, wikibase, wikicommons, size/L

#6979 database: Improve exception reporting, to debug flaky tests
  extensions/database/src/com/google/refine/extension/database/DatabaseServiceException.java
  extensions/database/src/com/google/refine/extension/database/mariadb/MariaDBConnectionManager.java
  extensions/database/src/com/google/refine/extension/database/mariadb/MariaDBDatabaseService.java
  extensions/database/src/com/google/refine/extension/database/mysql/MySQLConnectionManager.java
  extensions/database/src/com/google/refine/extension/database/mysql/MySQLDatabaseService.java
  extensions/database/src/com/google/refine/extension/database/pgsql/PgSQLConnectionManager.java
  extensions/database/src/com/google/refine/extension/database/pgsql/PgSQLDatabaseService.java
  extensions/database/src/com/google/refine/extension/database/sqlite/SQLiteConnectionManager.java
  extensions/database/src/com/google/refine/extension/database/sqlite/SQLiteDatabaseService.java
Labels: size/S

#7041 fix: issue #7038
  main/src/com/google/refine/importers/SeparatorBasedImporter.java
Labels: Type: Bug, Status: Pending Review

#6936 database: Re-enable test that fails in the CI
  extensions/database/tests/src/com/google/refine/extension/database/DatabaseImportControllerTest.java
Labels: Type: Bug, Status: Pending Review, tests, SQL/database, size/XS

#7040 Issue 3218 - Add "remove duplicate rows" menu item
  main/resources/com/google/refine/operations/OperationDescription.properties
  main/src/com/google/refine/commands/row/RemoveDuplicateRowsCommand.java
  main/src/com/google/refine/operations/row/RowDuplicatesRemovalOperation.java
  main/tests/server/src/com/google/refine/commands/row/RemoveDuplicateRowsCommandTest.java
  main/webapp/modules/core/MOD-INF/controller.js
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/dialogs/remove-duplicate-rows-dialog.html
  main/webapp/modules/core/scripts/dialogs/remove-duplicate-rows-dialog.js
  main/webapp/modules/core/scripts/views/data-table/data-table-view.js
  main/webapp/modules/core/styles/dialogs/remove-duplicate-rows-dialog.css
Labels: Type: Feature Request, design proposal needed
