Repository OpenRefine/OpenRefine, pull requests merged in 2024-07, with the labels that each got.

#6537 Solve Excel importing from URL problem Fixes #6418
  main/src/com/google/refine/importers/ImportingParserBase.java
  main/src/com/google/refine/importing/ImportingUtilities.java
  main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java
Labels: Type: Bug, XLS(X)

#6696 Fix preservation of pagination when matching a single cell
  main/tests/cypress/cypress/e2e/project/grid/column/reconcile/actions/cell-buttons.cy.js
  main/webapp/modules/core/scripts/views/data-table/cell-renderers/recon-renderer.js
Labels: Type: Bug, Theme: UX/Usability, reconciliation

#6631 Update pom.xml Adding David as Developer Emeritus
  pom.xml
Labels: maven

#6659 Add dialog to warn of history entry deletion
  main/tests/cypress/cypress/e2e/project/undo_redo/warn_for_history_deletion.cy.js
  main/webapp/modules/core/MOD-INF/controller.js
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/project.js
  main/webapp/modules/core/scripts/project/history-entry.html
  main/webapp/modules/core/scripts/project/history-panel.js
  main/webapp/modules/core/scripts/project/process-panel.js
  main/webapp/modules/core/scripts/util/confirm-history-erasure-dialog.html
  main/webapp/modules/core/styles/dialogs/confirm-history-erasure-dialog.less
Labels: Type: Feature Request, undo/redo/history

#6701 Fix type of error message returned by the Filter GREL control
  main/resources/com/google/refine/grel/ControlEvalError.properties
  main/src/com/google/refine/grel/controls/Filter.java
  main/tests/server/src/com/google/refine/grel/controls/FilterTests.java
Labels: Type: Bug, Good First Issue, grel

#6645 tests: Clean up unnecessary try-catch blocks
  main/tests/server/src/com/google/refine/ProjectManagerTests.java
  main/tests/server/src/com/google/refine/RefineServletTests.java
  main/tests/server/src/com/google/refine/commands/CommandTestBase.java
  main/tests/server/src/com/google/refine/commands/CommandTests.java
  main/tests/server/src/com/google/refine/commands/GetCSRFTokenCommandTest.java
  main/tests/server/src/com/google/refine/commands/browsing/GetClusteringFunctionsAndDistancesCommandTest.java
  main/tests/server/src/com/google/refine/commands/browsing/ScatterplotDrawCommandTests.java
  main/tests/server/src/com/google/refine/commands/cell/EditOneCellCommandTests.java
  main/tests/server/src/com/google/refine/commands/expr/ExpressionCommandTestBase.java
  main/tests/server/src/com/google/refine/commands/project/SetProjectMetadataCommandTests.java
  main/tests/server/src/com/google/refine/commands/project/SetProjectTagsCommandTests.java
  main/tests/server/src/com/google/refine/commands/recon/GuessTypesOfColumnCommandTests.java
  main/tests/server/src/com/google/refine/commands/recon/ReconJudgeOneCellCommandTest.java
  main/tests/server/src/com/google/refine/commands/row/GetRowsCommandTest.java
  main/tests/server/src/com/google/refine/commands/util/CancelProcessesCommandTests.java
  main/tests/server/src/com/google/refine/exporters/CsvExporterTests.java
  main/tests/server/src/com/google/refine/exporters/OdsExporterTests.java
  main/tests/server/src/com/google/refine/exporters/TemplatingExporterTests.java
  main/tests/server/src/com/google/refine/exporters/TsvExporterTests.java
  main/tests/server/src/com/google/refine/exporters/XlsExporterTests.java
  main/tests/server/src/com/google/refine/exporters/XlsxExporterTests.java
  main/tests/server/src/com/google/refine/exporters/sql/SqlExporterTests.java
  main/tests/server/src/com/google/refine/expr/util/JsonValueConverterTests.java
  main/tests/server/src/com/google/refine/grel/GrelTests.java
  main/tests/server/src/com/google/refine/grel/controls/ForEachTests.java
  main/tests/server/src/com/google/refine/grel/controls/ForRangeTests.java
  main/tests/server/src/com/google/refine/importers/ExcelImporterTests.java
  main/tests/server/src/com/google/refine/importers/FixedWidthImporterTests.java
  main/tests/server/src/com/google/refine/importers/JsonImporterTests.java
  main/tests/server/src/com/google/refine/importers/LineBasedImporterTests.java
  main/tests/server/src/com/google/refine/importers/OdsImporterTests.java
  main/tests/server/src/com/google/refine/importers/SeparatorBasedImporterTests.java
  main/tests/server/src/com/google/refine/importers/WikitextImporterTests.java
  main/tests/server/src/com/google/refine/importers/XmlImportUtilitiesTests.java
  main/tests/server/src/com/google/refine/importers/XmlImporterTests.java
  main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java
  main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java
  main/tests/server/src/com/google/refine/operations/recon/ReconOperationTests.java
  main/tests/server/src/com/google/refine/util/ParsingUtilitiesTests.java
  main/tests/server/src/com/google/refine/util/PatternSyntaxExceptionParserTests.java
Labels: Type: Feature Request, tests

#6461 Adds command for adding rows
  main/resources/com/google/refine/operations/OperationDescription.properties
  main/src/com/google/refine/commands/row/AddRowsCommand.java
  main/src/com/google/refine/model/changes/RowAdditionChange.java
  main/src/com/google/refine/operations/row/RowAdditionOperation.java
  main/tests/cypress/cypress/e2e/project/grid/all-column/add-rows.cy.js
  main/tests/data/changes/blank_row_addition.txt
  main/tests/server/src/com/google/refine/commands/row/AddRowsCommandTests.java
  main/tests/server/src/com/google/refine/model/changes/RowAdditionChangeTests.java
  main/tests/server/src/com/google/refine/operations/row/RowAdditionOperationTests.java
  main/webapp/modules/core/MOD-INF/controller.js
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/dialogs/add-rows-dialog.html
  main/webapp/modules/core/scripts/dialogs/add-rows-dialog.js
  main/webapp/modules/core/scripts/views/data-table/data-table-view.js
Labels: Type: Feature Request, extension, gsoc/outreachy

#6620 Replace PNG logo by SVG equivalent
  main/webapp/modules/core/about.html
  main/webapp/modules/core/error.vt
  main/webapp/modules/core/images/logo-gem-126.svg
  main/webapp/modules/core/index.vt
  main/webapp/modules/core/preferences.vt
  main/webapp/modules/core/project.vt
  main/webapp/modules/core/styles/project/sidebar.css
Labels: Type: Feature Request, Good First Issue, Theme: UI/Visual

#6653 Restore public API. Fixes #6652
  extensions/wikibase/tests/src/org/openrefine/wikibase/editing/NewEntityLibraryTest.java
  main/pom.xml
  main/src/com/google/refine/importers/WikitextImporter.java
  main/src/com/google/refine/model/recon/DataExtensionReconConfig.java
  main/src/com/google/refine/model/recon/ReconConfig.java
  main/src/com/google/refine/model/recon/StandardReconConfig.java
  main/src/com/google/refine/operations/recon/ReconMarkNewTopicsOperation.java
  main/src/com/google/refine/operations/recon/ReconUseValuesAsIdentifiersOperation.java
  main/src/com/google/refine/util/ParsingUtilities.java
  main/tests/server/src/com/google/refine/commands/recon/ReconJudgeOneCellCommandTest.java
  main/tests/server/src/com/google/refine/model/ColumnTests.java
  main/tests/server/src/com/google/refine/model/recon/StandardReconConfigTests.java
  main/tests/server/src/com/google/refine/operations/recon/ReconJudgeSimilarCellsOperationTests.java
  main/tests/server/src/com/google/refine/operations/recon/ReconMarkNewTopicsOperationTests.java
  main/tests/server/src/com/google/refine/operations/recon/ReconOperationTests.java
Labels: Type: Bug, extension, Module: API

#6725 Update CONTRIBUTING.md to remove mention of other distributions.
  CONTRIBUTING.md
Labels: Type: Bug, Priority: Medium

#6705 UI Clustering: Add management dialog
  main/tests/cypress/cypress/e2e/project/grid/column/edit-cells/cluster-and-edit.cy.js
  main/webapp/modules/core/MOD-INF/controller.js
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/dialogs/add-function-dialog.html
  main/webapp/modules/core/scripts/dialogs/clustering-dialog.html
  main/webapp/modules/core/scripts/dialogs/clustering-dialog.js
  main/webapp/modules/core/scripts/dialogs/clustering-functions-dialog.html
  main/webapp/modules/core/scripts/dialogs/clustering-functions-dialog.js
  main/webapp/modules/core/scripts/facets/list-facet.js
  main/webapp/modules/core/scripts/project/browsing-engine.js
  main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js
  main/webapp/modules/core/styles/dialogs/clustering-dialog.css
  main/webapp/modules/core/styles/dialogs/clustering-functions-dialog.css
Labels: Type: Feature Request

#6546 Preserve pagination after actions which trigger a grid update
  extensions/database/module/scripts/index/database-import-controller.js
  extensions/wikibase/module/scripts/dialogs/perform-edits-dialog.js
  main/src/com/google/refine/browsing/Engine.java
  main/src/com/google/refine/browsing/RecordVisitor.java
  main/src/com/google/refine/browsing/RowVisitor.java
  main/src/com/google/refine/browsing/facets/ScatterplotDrawingRowVisitor.java
  main/src/com/google/refine/browsing/util/ConjunctiveFilteredRecords.java
  main/src/com/google/refine/browsing/util/ConjunctiveFilteredRows.java
  main/src/com/google/refine/browsing/util/RowVisitorAsRecordVisitor.java
  main/src/com/google/refine/commands/row/GetRowsCommand.java
  main/src/com/google/refine/sorting/SortingRecordVisitor.java
  main/src/com/google/refine/sorting/SortingRowVisitor.java
  main/tests/cypress/cypress/e2e/project/grid/viewpanel-header/pagination.cy.js
  main/tests/server/src/com/google/refine/browsing/util/ExpressionNominalValueGrouperTests.java
  main/tests/server/src/com/google/refine/commands/row/GetRowsCommandTest.java
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/langs/translation-es.json
  main/webapp/modules/core/langs/translation-fr.json
  main/webapp/modules/core/scripts/dialogs/clustering-dialog.js
  main/webapp/modules/core/scripts/dialogs/column-reordering-dialog.js
  main/webapp/modules/core/scripts/dialogs/common-transform-dialog.js
  main/webapp/modules/core/scripts/dialogs/expression-column-dialog.js
  main/webapp/modules/core/scripts/index/default-importing-controller/controller.js
  main/webapp/modules/core/scripts/project.js
  main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
  main/webapp/modules/core/scripts/views/data-table/cell-renderers/recon-renderer.js
  main/webapp/modules/core/scripts/views/data-table/data-table-view.js
  main/webapp/modules/core/scripts/views/data-table/menu-edit-cells.js
  main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
  main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js
Labels: Type: Bug, Type: Feature Request, Priority: Medium, Theme: UX/Usability, Module: Frontend, reconciliation, undo/redo/history, records, grid pagination / scrolling

#6748 Fix flaky Cypress tests
  main/tests/cypress/cypress/e2e/create-project/preview_project.cy.js
  main/tests/cypress/cypress/e2e/project/grid/column/facet/facets.numeric.cy.js
  main/tests/cypress/cypress/e2e/project/grid/column/transpose/cell_accross_columns.cy.js
  main/tests/cypress/cypress/e2e/project/grid/column/transpose/columnize.cy.js
  main/tests/cypress/cypress/support/commands.js
  main/tests/cypress/cypress/support/e2e.js
Labels: Type: Bug, tests, CI/CD
