Repository OpenRefine/OpenRefine, pull requests merged in 2024-11, with the labels that each got.

#6930 Update license folder locations in README
  README.md
Labels: PR: Documentation

#6981 Assign different cascade layers to CSS from different modules
  main/webapp/modules/core/MOD-INF/controller.js
Labels: extension

#6965 fixes #6672 : Set a delay between opening submenu and hover.
  main/webapp/modules/core/scripts/util/menu.js
  main/webapp/modules/core/styles/util/menu.css
Labels: Type: Feature Request, Theme: UX/Usability, Good First Issue

#6993 Update CI action names
  .github/workflows/pull_request_e2e.yml
  .github/workflows/pull_request_server.yml
Labels: size/XS

#6995 ignore .vscode/ settings like we do for .idea/
  .gitignore
Labels: size/XS

#6978 Fix inclusion of CSRF token in QuickStatements export
  extensions/wikibase/module/scripts/menu-bar-extension.js
Labels: Type: Bug, Status: Pending Review, size/S

#7003 Mark tables used for layout as presentational
  main/webapp/modules/core/about.html
  main/webapp/modules/core/scripts/dialogs/add-function-dialog.html
  main/webapp/modules/core/scripts/dialogs/column-reordering-dialog.html
  main/webapp/modules/core/scripts/dialogs/custom-tabular-exporter-dialog.html
  main/webapp/modules/core/scripts/dialogs/export-project-dialog.html
  main/webapp/modules/core/scripts/dialogs/expression-column-dialog.html
  main/webapp/modules/core/scripts/dialogs/expression-preview-dialog.html
  main/webapp/modules/core/scripts/dialogs/scatterplot-dialog.html
  main/webapp/modules/core/scripts/dialogs/sql-exporter-dialog.html
  main/webapp/modules/core/scripts/dialogs/templating-exporter-dialog.html
  main/webapp/modules/core/scripts/facets/list-facet.js
  main/webapp/modules/core/scripts/facets/range-facet.js
  main/webapp/modules/core/scripts/facets/scatterplot-facet.js
  main/webapp/modules/core/scripts/facets/text-search-facet.js
  main/webapp/modules/core/scripts/facets/timerange-facet.js
  main/webapp/modules/core/scripts/index/create-project-error-panel.html
  main/webapp/modules/core/scripts/index/create-project-progress-panel.html
  main/webapp/modules/core/scripts/index/default-importing-controller/file-selection-panel.html
  main/webapp/modules/core/scripts/index/default-importing-controller/parsing-panel.html
  main/webapp/modules/core/scripts/index/default-importing-sources/import-from-clipboard-form.html
  main/webapp/modules/core/scripts/index/default-importing-sources/import-from-computer-form.html
  main/webapp/modules/core/scripts/index/default-importing-sources/import-from-web-form.html
  main/webapp/modules/core/scripts/index/import-project-ui.html
  main/webapp/modules/core/scripts/index/lang-settings-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/excel-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/fixed-width-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/json-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/line-based-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/rdf-triples-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/separator-based-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.html
  main/webapp/modules/core/scripts/index/parser-interfaces/xml-parser-ui.html
  main/webapp/modules/core/scripts/project/history-extract-dialog.html
  main/webapp/modules/core/scripts/reconciliation/standard-service-panel.html
  main/webapp/modules/core/scripts/util/menu.js
  main/webapp/modules/core/scripts/views/data-table/add-column-by-fetching-urls-dialog.html
  main/webapp/modules/core/scripts/views/data-table/add-column-by-reconciliation.html
  main/webapp/modules/core/scripts/views/data-table/add-column-dialog.html
  main/webapp/modules/core/scripts/views/data-table/add-q-column-dialog.html
  main/webapp/modules/core/scripts/views/data-table/cell-recon-search-for-match.html
  main/webapp/modules/core/scripts/views/data-table/copy-recon-across-columns-dialog.html
  main/webapp/modules/core/scripts/views/data-table/key-value-columnize.html
  main/webapp/modules/core/scripts/views/data-table/replace-dialog.html
  main/webapp/modules/core/scripts/views/data-table/sorting-criterion-dialog.html
  main/webapp/modules/core/scripts/views/data-table/split-column-dialog.html
  main/webapp/modules/core/scripts/views/data-table/split-multi-valued-cells-dialog.html
  main/webapp/modules/core/scripts/views/data-table/text-transform-dialog.html
  main/webapp/modules/core/scripts/views/data-table/transpose-columns-into-rows.html
  main/webapp/modules/core/scripts/views/data-table/warn-of-pending-sort.html
Labels: Module: Frontend, Theme: accessibility

#6845 fix resultSummary div in Clustering dialog has unnecessary squishyness
  main/webapp/modules/core/styles/dialogs/clustering-dialog.css
Labels: Type: Bug, Module: Frontend, Good First Issue, clustering, Type: Design Discussions, Theme: UI/Visual, size/XS

#6136 Wikibase: proxy manifest requests
  extensions/wikibase/module/MOD-INF/controller.js
  extensions/wikibase/module/scripts/wikibase-manager.js
  extensions/wikibase/src/org/openrefine/wikibase/commands/FetchManifestCommand.java
Labels: wikibase, size/S

#6975 Add an extension mangement page
  extensions/wikibase/module/styles/schema-alignment.css
  main/src/com/google/refine/commands/OpenExtensionsDirCommand.java
  main/webapp/modules/core/MOD-INF/controller.js
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/index/manage-extensions-ui.html
  main/webapp/modules/core/scripts/index/manage-extensions-ui.js
  main/webapp/modules/core/styles/common.css
  server/src/com/google/refine/Refine.java
Labels: extension, size/L

#7016 Really fix QuickStatements export this time
  extensions/wikibase/module/scripts/menu-bar-extension.js
  main/tests/cypress/cypress/e2e/extensions/wikibase/quickstatements_export.cy.js
  main/tests/cypress/cypress/fixtures/wikidata-schema.tar.gz.zip
Labels: Type: Bug, Status: Pending Review

#6908 Introduce AbstractOperation::validate() to check operation parameters
  main/src/com/google/refine/commands/history/ApplyOperationsCommand.java
  modules/core/src/main/java/com/google/refine/model/AbstractOperation.java
Labels: size/XS

#7022 fix: Remove spurious recon logo warnings
  extensions/wikibase/module/scripts/schema-alignment.js
  main/webapp/modules/core/scripts/views/data-table/column-header-ui.js
Labels: Type: Bug, reconciliation
