Repository OpenRefine/OpenRefine, pull requests merged in 2024-01, with the labels that each got.

#6278 Fix e2e_tests (Cypress). Fixes #6271
  refine
Labels: Type: Bug, tests

#6244 Improves the display of reconciliation results
  main/tests/cypress/cypress/e2e/project/grid/column/reconcile/actions/see-more-and-see-less.cy.js
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/views/data-table/cell-renderers/recon-renderer.js
  main/webapp/modules/core/styles/views/data-table-view.css
Labels: Type: Feature Request, Module: Frontend, reconciliation, Theme: UI/Visual

#6293 Fix setting the log level from the command line
  refine.bat
  server/src/com/google/refine/Refine.java
Labels: Type: Bug, Good First Issue, logging

#6285 Improve how to indicate the data source following data extension#5130
  main/src/com/google/refine/model/Column.java
  main/src/com/google/refine/model/changes/DataExtensionChange.java
  main/tests/server/src/com/google/refine/model/ColumnTests.java
  main/tests/server/src/com/google/refine/operations/recon/ExtendDataOperationTests.java
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/views/data-table/column-header-ui.js
Labels: Type: Feature Request, Module: Frontend, wikibase, wikicommons

#6318 Issue 6304 unfolding triangle bug
  extensions/wikibase/module/scripts/preview-renderer.js
Labels: Type: Feature Request, Theme: UX/Usability, Good First Issue, wikibase

#6327 Fix wiring of event listeners in recon dialog
  main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
Labels: Type: Bug, Theme: UX/Usability, reconciliation
