Repository OpenRefine/OpenRefine, pull requests merged in 2024-03, with the labels that each got.

#6397 Fix recon dialog suggested types radio button
  main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
Labels: Type: Feature Request, Good First Issue, Theme: accessibility

#6407 Remove use of Properties for URL query parsing, fixes #6403
  extensions/database/src/com/google/refine/extension/database/DatabaseImportController.java
  extensions/database/tests/src/com/google/refine/extension/database/DatabaseImportControllerTest.java
  extensions/gdata/src/com/google/refine/extension/gdata/GDataImportingController.java
  main/src/com/google/refine/commands/Command.java
  main/src/com/google/refine/commands/importing/ImportingControllerCommand.java
  main/src/com/google/refine/commands/project/CreateProjectCommand.java
  main/src/com/google/refine/commands/project/ImportProjectCommand.java
  main/src/com/google/refine/importing/DefaultImportingController.java
  main/src/com/google/refine/importing/ImportingUtilities.java
  main/src/com/google/refine/util/ParsingUtilities.java
  main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java
  main/tests/server/src/com/google/refine/util/ParsingUtilitiesTests.java
Labels: Type: Feature Request, refactoring

#6383 Introduce test utility to compare project contents
  main/src/com/google/refine/model/Cell.java
  main/tests/server/src/com/google/refine/RefineTest.java
  main/tests/server/src/com/google/refine/importers/ExcelImporterTests.java
  main/tests/server/src/com/google/refine/importers/FixedWidthImporterTests.java
  main/tests/server/src/com/google/refine/importers/JsonImporterTests.java
  main/tests/server/src/com/google/refine/importers/LineBasedImporterTests.java
  main/tests/server/src/com/google/refine/importers/MarcImporterTests.java
  main/tests/server/src/com/google/refine/importers/OdsImporterTests.java
  main/tests/server/src/com/google/refine/importers/RdfTripleImporterTests.java
  main/tests/server/src/com/google/refine/importers/SeparatorBasedImporterTests.java
  main/tests/server/src/com/google/refine/importers/WikitextImporterTests.java
  main/tests/server/src/com/google/refine/operations/cell/BlankDownTests.java
  main/tests/server/src/com/google/refine/operations/cell/FillDownTests.java
  main/tests/server/src/com/google/refine/operations/cell/JoinMultiValuedCellsTests.java
  main/tests/server/src/com/google/refine/operations/cell/KeyValueColumnizeTests.java
  main/tests/server/src/com/google/refine/operations/cell/SplitMultiValuedCellsTests.java
  main/tests/server/src/com/google/refine/operations/cell/TransposeColumnsIntoRowsOperationTest.java
  main/tests/server/src/com/google/refine/operations/column/ColumnReorderOperationTests.java
  main/tests/server/src/com/google/refine/operations/recon/ExtendDataOperationTests.java
  main/tests/server/src/com/google/refine/operations/row/RowReorderOperationTests.java
Labels: Type: Feature Request, tests

#6415 Fix swapped button labels in wikibase schema editor
  extensions/wikibase/module/scripts/schema-alignment.js
Labels: Type: Bug, wikibase, Theme: UI/Visual

#6429 [#3243] Ignore JSON comments by default
  main/src/com/google/refine/importers/JsonImporter.java
  main/tests/server/src/com/google/refine/importers/JsonImporterTests.java
Labels: Type: Feature Request, Good First Issue, JSON

#6442 Fixes #6406. Corrects behavior of cell editing when confirming single cell changes with "Enter."
  main/webapp/modules/core/scripts/views/data-table/cell-ui.js
Labels: Type: Bug, Theme: UX/Usability, Good First Issue

#6450 Fix inconsistent Extract/Apply button location
  main/webapp/modules/core/scripts/project/history-panel.html
Labels: Type: Bug, Theme: UX/Usability

#6468 Remove Denormalize operation
  main/resources/com/google/refine/operations/OperationDescription.properties
  main/src/com/google/refine/commands/row/DenormalizeCommand.java
  main/src/com/google/refine/operations/row/DenormalizeOperation.java
  main/tests/server/src/com/google/refine/commands/row/DenormalizeCommandTests.java
  main/tests/server/src/com/google/refine/operations/row/DenormalizeOperationTests.java
  main/webapp/modules/core/MOD-INF/controller.js
Labels: maintainability

#6473 Removed grey background from button tag
  main/webapp/modules/core/styles/views/data-table-view.css
Labels: Type: Bug, Good First Issue, Theme: UI/Visual

#6478 Provide slf4j-api & jackson to extension modules. Fixes #6475
  extensions/database/pom.xml
  extensions/gdata/pom.xml
  extensions/jython/pom.xml
  extensions/pc-axis/pom.xml
  extensions/wikibase/pom.xml
  server/src/com/google/util/logging/IndentingLayout.java
Labels: Type: Bug, extension, maven

#6474 Fix project name lookup with missing metadata. Fixes #6453
  main/src/com/google/refine/ProjectManager.java
  main/src/com/google/refine/history/History.java
  main/src/com/google/refine/io/FileHistoryEntryManager.java
  main/src/com/google/refine/io/FileProjectManager.java
  main/src/com/google/refine/io/ProjectMetadataUtilities.java
  main/src/com/google/refine/io/ProjectUtilities.java
  main/src/com/google/refine/model/Column.java
  main/src/com/google/refine/model/ColumnModel.java
  main/src/com/google/refine/model/Project.java
  main/src/com/google/refine/model/Recon.java
  main/src/com/google/refine/model/ReconCandidate.java
  main/src/com/google/refine/model/Row.java
  main/src/com/google/refine/util/Pool.java
  main/tests/server/src/com/google/refine/expr/functions/CrossTests.java
  main/tests/server/src/com/google/refine/io/FileProjectManagerTests.java
Labels: Type: Bug

#6482 Issue 6353 implement Windows ordering buttons ("OK" / "Cancel")
  extensions/wikibase/module/scripts/dialogs/wikibase-dialog.html
  main/webapp/modules/core/scripts/dialogs/column-reordering-dialog.html
  main/webapp/modules/core/scripts/dialogs/common-transform-dialog.html
  main/webapp/modules/core/scripts/dialogs/expression-column-dialog.html
  main/webapp/modules/core/scripts/views/data-table/add-column-by-fetching-urls-dialog.html
  main/webapp/modules/core/scripts/views/data-table/add-column-by-reconciliation.html
  main/webapp/modules/core/scripts/views/data-table/add-column-dialog.html
  main/webapp/modules/core/scripts/views/data-table/add-q-column-dialog.html
  main/webapp/modules/core/scripts/views/data-table/cell-editor.html
  main/webapp/modules/core/scripts/views/data-table/column-join.html
  main/webapp/modules/core/scripts/views/data-table/copy-recon-across-columns-dialog.html
  main/webapp/modules/core/scripts/views/data-table/key-value-columnize.html
  main/webapp/modules/core/scripts/views/data-table/rename-column.html
  main/webapp/modules/core/scripts/views/data-table/replace-dialog.html
  main/webapp/modules/core/scripts/views/data-table/sorting-criterion-dialog.html
  main/webapp/modules/core/scripts/views/data-table/split-column-dialog.html
  main/webapp/modules/core/scripts/views/data-table/split-multi-valued-cells-dialog.html
  main/webapp/modules/core/scripts/views/data-table/text-transform-dialog.html
  main/webapp/modules/core/scripts/views/data-table/transpose-columns-into-rows.html
  main/webapp/modules/core/scripts/views/data-table/warn-of-pending-sort.html
  main/webapp/modules/core/styles/reconciliation/recon-dialog.css
Labels: Type: Feature Request, Theme: UX/Usability, Good First Issue

#6483 Fix recon deserialization error for matched cells
  main/src/com/google/refine/model/Recon.java
  main/tests/server/src/com/google/refine/model/ReconTests.java
Labels: Type: Bug, reconciliation, error handling

#6476 Issue 6469 improve test coverage
  main/src/com/google/refine/expr/util/CalendarParser.java
  main/tests/server/src/com/google/refine/expr/util/CalenderParserTest.java
Labels: maintainability, Good First Issue, tests

#6486 Drop legacy Keyer classes not registered as clustering methods
  main/src/com/google/refine/clustering/binning/DoubleMetaphoneKeyer.java
  main/src/com/google/refine/clustering/binning/KeyerFactory.java
  main/src/com/google/refine/clustering/binning/MetaphoneKeyer.java
  main/src/com/google/refine/clustering/binning/SoundexKeyer.java
  main/src/com/google/refine/clustering/knn/DistanceFactory.java
  main/src/com/google/refine/expr/functions/strings/Phonetic.java
  main/tests/server/src/com/google/refine/expr/functions/strings/PhoneticTests.java
Labels: maintainability, clustering

#6438 Added a new feature to import files using drag and drop. Requested in issue #6250
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/index/default-importing-sources/import-from-computer-form.html
  main/webapp/modules/core/scripts/index/default-importing-sources/sources.js
  main/webapp/modules/core/styles/index/default-importing-sources.css
Labels: Type: Feature Request, Theme: UX/Usability, Good First Issue
