Repository OpenRefine/OpenRefine, pull requests merged in 2024-05, with the labels that each got.

#6567 refine script: Abort build early if NPM is missing
  refine
Labels: Type: Bug

#6484 Drop 'sample' extension.
  extensions/sample/.gitignore
  extensions/sample/.settings/org.eclipse.jdt.core.prefs
  extensions/sample/.settings/org.eclipse.jdt.ui.prefs
  extensions/sample/.settings/org.eclipse.wst.common.project.facet.core.xml
  extensions/sample/.settings/org.eclipse.wst.jsdt.ui.superType.container
  extensions/sample/.settings/org.eclipse.wst.jsdt.ui.superType.name
  extensions/sample/module/MOD-INF/controller.js
  extensions/sample/module/MOD-INF/module.properties
  extensions/sample/module/index.vt
  extensions/sample/module/macros.vm
  extensions/sample/module/scripts/project-injection.js
  extensions/sample/module/styles/project-injection.css
  extensions/sample/pom.xml
  extensions/sample/src/com/google/refine/sampleExtension/SampleUtil.java
Labels: maintainability, maven

#6590 exclude oro license from trying to download
  packaging/pom.xml
Labels: maintainability, maven

#6600 recon: Add back missing 'search for match' button
  main/tests/cypress/cypress/e2e/project/grid/column/reconcile/actions/cell-buttons.cy.js
  main/tests/cypress/cypress/fixtures/reconciled-project-no-match.zip
  main/webapp/modules/core/scripts/views/data-table/cell-renderers/recon-renderer.js
Labels: Type: Bug, reconciliation

#6606 Fix NullPointerException in forEachIndex
  main/src/com/google/refine/expr/functions/arrays/Join.java
  main/src/com/google/refine/grel/controls/ForEachIndex.java
  main/tests/server/src/com/google/refine/expr/functions/arrays/JoinTests.java
  main/tests/server/src/com/google/refine/grel/controls/ForEachIndexTests.java
Labels: Type: Bug, grel

#6603 Use correct WAI-ARIA role
  main/webapp/modules/core/scripts/util/dialog.js
Labels: maintainability, Theme: accessibility

#6448 Issue 105 exclude candidates from cluster
  main/tests/cypress/cypress/e2e/project/grid/column/edit-cells/cluster-and-edit.cy.js
  main/webapp/modules/core/scripts/dialogs/clustering-dialog.js
Labels: Type: Feature Request, Priority: Medium, Theme: UX/Usability, logic, Module: Frontend, clustering

#6626 Checking running status of OpenRefine with wget will not work correct…
  refine
Labels: Type: Bug, Good First Issue

#6552 wikibase: Better handling of the 'badtags' error
  extensions/wikibase/module/scripts/wikibase-manager.js
  extensions/wikibase/src/org/openrefine/wikibase/editing/EditBatchProcessor.java
  extensions/wikibase/src/org/openrefine/wikibase/manifests/Manifest.java
  extensions/wikibase/src/org/openrefine/wikibase/operations/PerformWikibaseEditsOperation.java
  extensions/wikibase/tests/src/org/openrefine/wikibase/editing/EditBatchProcessorTest.java
  extensions/wikibase/tests/src/org/openrefine/wikibase/operations/PerformWikibaseEditsOperationTest.java
Labels: Type: Bug, wikibase

#6592 feat: openrefine icon compliant with new MacOS guidelines
  graphics/icon/openrefine.icns
Labels: Type: Feature Request, Theme: UX/Usability, Platform: macOS, Type: Design Discussions
