Repository OpenRefine/OpenRefine, pull requests merged in 2024-06, with the labels that each got.

#6661 Move commons-lang3 dependency to the server module
  main/pom.xml
  server/pom.xml
Labels: Type: Bug, Status: Pending Review

#6648 Improve localization of row/record count bar
  main/tests/cypress/cypress/e2e/tutorial/layout-of-openrefine.cy.js
  main/tests/cypress/cypress/support/commands.js
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/project/summary-bar.js
Labels: Type: Bug, localization

#6684 Fix join() of arrays containing nulls. Fixes #6683
  main/src/com/google/refine/expr/functions/arrays/Join.java
  main/tests/server/src/com/google/refine/expr/functions/arrays/JoinTests.java
Labels: Type: Bug, grel
