Repository OpenRefine/OpenRefine, pull requests merged in 2025-02, with the labels that each got.

#7115 Fixes #7114 make refine.bat exit on errors from external programs
  refine.bat
Labels: Type: Bug, Status: Pending Review, Platform: Windows

#7120 Update LoadLanguageCommand.java
  main/src/com/google/refine/commands/lang/LoadLanguageCommand.java
Labels: Type: Bug, Good First Issue, localization, logging

#7123 fix: Windows installer removes previous install
  packaging/openrefine.iss
Labels: Type: Bug, Status: Pending Review, Platform: Windows

#7130 Fixes missing wmic command output running refine.bat if Powershell
  refine.bat
Labels: Platform: Windows, size/XS

#7127 fixes #6608 - Expose diacritics normalization used in fingerprint()
  modules/grel/src/main/java/com/google/refine/expr/functions/strings/Normalize.java
  modules/grel/src/main/java/com/google/refine/grel/ControlFunctionRegistry.java
  modules/grel/src/main/resources/com/google/refine/grel/FunctionDescription.properties
  modules/grel/src/test/java/com/google/refine/expr/functions/strings/NormalizeTests.java
Labels: Type: Feature Request, Good First Issue, localization, grel

#7108 fix: Correct home page behaviour when there are no events to advertise
  main/webapp/modules/core/scripts/index.js
Labels: Type: Bug

#7139 fix typos for chomp English translation
  modules/grel/src/main/resources/com/google/refine/grel/FunctionDescription.properties
Labels: PR: Documentation

#7145 move rename and remove column one menu up
  main/tests/cypress/cypress/e2e/project/grid/column/edit-column/rename_remove_column.cy.js
  main/tests/cypress/cypress/e2e/project/undo_redo/undo_redo.cy.js
  main/tests/cypress/cypress/support/commands.js
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/views/data-table/column-header-ui.js
  main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
Labels: Type: Feature Request, Theme: UX/Usability, Good First Issue
