Repository OpenRefine/OpenRefine, pull requests merged in 2025-03, with the labels that each got.

#7176 fix: weird layout for wikitext importer
  main/webapp/modules/core/scripts/index/parser-interfaces/wikitext-parser-ui.html
Labels: Type: Bug, Good First Issue, wikitable, Theme: UI/Visual

#7187 Fix infinite loading spinner for invalid or unknown project IDs
  main/src/com/google/refine/commands/project/GetModelsCommand.java
Labels: Type: Bug

#7173 Show Undo notification when applying recipes
  main/src/com/google/refine/commands/history/ApplyOperationsCommand.java
  main/tests/cypress/cypress/e2e/project/undo_redo/apply.cy.js
  main/tests/server/src/com/google/refine/commands/history/ApplyOperationsCommandTests.java
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/project.js
  main/webapp/modules/core/scripts/project/process-panel.js
Labels: Type: Feature Request, Status: Pending Review

#7197 fixes 7010: open file manager with headless Java
  modules/core/src/main/java/com/google/refine/util/OpenDirectoryUtilities.java
Labels: Type: Bug

#7201 Fix pagination controls and row range
  main/src/com/google/refine/commands/row/GetRowsCommand.java
  main/tests/cypress/cypress/e2e/project/grid/viewpanel-header/pagination.cy.js
  main/tests/server/src/com/google/refine/commands/row/GetRowsCommandTest.java
  main/webapp/modules/core/scripts/views/data-table/data-table-view.js
Labels: Type: Bug, Priority: High, tests, grid pagination / scrolling, Difficulty: Intermediate

#7168 Show all column headers in full by default
  main/webapp/modules/core/scripts/views/data-table/data-table-view.js
  main/webapp/modules/core/styles/views/data-table-view.css
Labels: Type: Bug

#7191 fix: Disable maximum string length in Jackson
  modules/core/src/main/java/com/google/refine/util/ParsingUtilities.java
Labels: Type: Bug, persistence, Priority: High

#7166 Fix layout of menu icons for long descriptions
  main/webapp/modules/core/scripts/util/menu.js
  main/webapp/modules/core/styles/util/menu.css
Labels: Type: Bug

#7211 Send absolute row index in request when "last" pagination button is clicked
  main/src/com/google/refine/commands/row/GetRowsCommand.java
  main/tests/server/src/com/google/refine/commands/row/GetRowsCommandTest.java
Labels: Type: Bug, Status: Pending Review

#7174 Improve generalizability of the "column move" operation
  main/resources/com/google/refine/operations/OperationDescription.properties
  main/src/com/google/refine/operations/column/AbstractColumnMoveOperation.java
  main/src/com/google/refine/operations/column/ColumnMoveFirstOperation.java
  main/src/com/google/refine/operations/column/ColumnMoveLastOperation.java
  main/src/com/google/refine/operations/column/ColumnMoveLeftOperation.java
  main/src/com/google/refine/operations/column/ColumnMoveOperation.java
  main/src/com/google/refine/operations/column/ColumnMoveRightOperation.java
  main/tests/cypress/cypress/e2e/project/grid/column/edit-column/reposition_column.cy.js
  main/tests/server/src/com/google/refine/operations/column/ColumnMoveFirstOperationTests.java
  main/tests/server/src/com/google/refine/operations/column/ColumnMoveLastOperationTests.java
  main/tests/server/src/com/google/refine/operations/column/ColumnMoveLeftOperationTests.java
  main/tests/server/src/com/google/refine/operations/column/ColumnMoveRightOperationTests.java
  main/webapp/modules/core/MOD-INF/controller.js
  main/webapp/modules/core/scripts/project/operation-icons.js
  main/webapp/modules/core/scripts/views/data-table/menu-edit-column.js
Labels: Type: Feature Request, undo/redo/history
