Repository OpenRefine/OpenRefine, pull requests merged in 2025-05, with the labels that each got.

#7292 wikibase: fix NoValueSnak being incorrectly cast
  extensions/wikibase/src/org/openrefine/wikibase/schema/strategies/QualifiersStatementMerger.java
Labels: Type: Bug, wikibase

#7296 Proposal: Add JSDoc annotations to JavaScript extension points
  main/webapp/modules/core/scripts/util/dialog.js
Labels: Module: Frontend, extension

#7301 feat(ui): enable drag‑and‑drop column header reordering in DataTable view
  main/webapp/modules/core/scripts/views/data-table/data-table-view.js
Labels: Type: Feature Request
