Repository OpenRefine/OpenRefine, pull requests merged in 2025-04, with the labels that each got.

#7243 Enable custom clustering for non-GREL expressions
  extensions/jython/src/com/google/refine/jython/JythonEvaluable.java
  extensions/jython/tests/src/com/google/refine/jython/JythonEvaluableTest.java
  main/src/com/google/refine/clustering/binning/UserDefinedKeyer.java
  main/src/com/google/refine/clustering/knn/UserDefinedDistance.java
  main/src/com/google/refine/expr/ClojureParser.java
  main/tests/server/src/com/google/refine/clustering/binning/UserDefinedKeyerTests.java
  main/tests/server/src/com/google/refine/clustering/knn/DistanceTests.java
  main/tests/server/src/com/google/refine/expr/ClojureParserTest.java
  main/webapp/modules/core/scripts/dialogs/clustering-dialog.js
  main/webapp/modules/core/scripts/dialogs/clustering-functions-dialog.js
  main/webapp/modules/core/scripts/dialogs/expression-preview-dialog.js
Labels: Type: Bug, Status: Pending Review

#7247 Fix deserialization of RowAdditionOperation.
  main/src/com/google/refine/operations/row/RowAdditionOperation.java
  main/tests/server/src/com/google/refine/operations/row/RowAdditionOperationTests.java
  modules/core/src/main/java/com/google/refine/model/Cell.java
  modules/core/src/main/java/com/google/refine/model/Row.java
  modules/core/src/main/java/com/google/refine/model/changes/RowAdditionChange.java
  modules/core/src/test/java/com/google/refine/model/CellTests.java
  modules/core/src/test/java/com/google/refine/model/RowTests.java
  modules/core/src/test/java/com/google/refine/model/changes/RowAdditionChangeTests.java
Labels: Type: Bug, Priority: High

#7193 closes #6281: renaming "view" options for columns in menu
  main/webapp/modules/core/langs/translation-en.json
Labels: Type: Feature Request, Theme: UX/Usability, Good First Issue

#7253 add upload button to preview tab
  extensions/wikibase/module/scripts/preview-tab.html
  extensions/wikibase/module/scripts/schema-alignment.js
  extensions/wikibase/module/styles/schema-alignment.css
Labels: Type: Feature Request, Theme: UX/Usability, Good First Issue, wikibase
