Repository OpenRefine/OpenRefine, pull requests merged in 2025-01, with the labels that each got.

#6929 core: Introduce getSource() and getLanguagePrefix() on Evaluable
  extensions/jython/src/com/google/refine/jython/JythonEvaluable.java
  extensions/jython/tests/src/com/google/refine/jython/JythonEvaluableTest.java
  main/src/com/google/refine/expr/ClojureParser.java
  modules/core/src/main/java/com/google/refine/browsing/facets/TextSearchFacet.java
  modules/core/src/main/java/com/google/refine/expr/Evaluable.java
  modules/core/src/main/java/com/google/refine/expr/LanguageSpecificParser.java
  modules/core/src/main/java/com/google/refine/expr/MetaParser.java
  modules/core/src/test/java/com/google/refine/browsing/util/ExpressionNominalValueGrouperTests.java
  modules/grel/src/main/java/com/google/refine/grel/Parser.java
  modules/grel/src/main/java/com/google/refine/grel/ast/ArrayExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/BracketedExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/ControlCallExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/FieldAccessorExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/FunctionCallExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/GrelExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/LiteralExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/OperatorCallExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/VariableExpr.java
  modules/grel/src/test/java/com/google/refine/grel/GrelTests.java
  modules/grel/src/test/java/com/google/refine/grel/ast/ArrayExprTest.java
  modules/grel/src/test/java/com/google/refine/grel/ast/BracketedExprTest.java
  modules/grel/src/test/java/com/google/refine/grel/ast/ControlCallExprTest.java
  modules/grel/src/test/java/com/google/refine/grel/ast/FunctionCallExprTest.java
  modules/grel/src/test/java/com/google/refine/grel/ast/OperatorCallExprTest.java
Labels: size/M

#4690 Search filter for Open Projects page
  main/tests/cypress/cypress/e2e/open-project/filter_projects.cy.js
  main/webapp/modules/core/MOD-INF/controller.js
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/index/open-project-ui.html
  main/webapp/modules/core/scripts/index/open-project-ui.js
  main/webapp/modules/core/scripts/util/filter-lists-search.js
  main/webapp/modules/core/styles/index/open-project-ui.css
Labels: Type: Feature Request, Module: Frontend

#6715 Add escape() function options to escape URL path and fragment
  modules/grel/src/main/java/com/google/refine/expr/functions/strings/Escape.java
  modules/grel/src/main/resources/com/google/refine/grel/FunctionDescription.properties
  modules/grel/src/test/java/com/google/refine/expr/functions/strings/EscapeTests.java
Labels: Type: Feature Request, Priority: Low, Good First Issue, grel, size/M

#7053 wikibase: Improve recon name for created entities
  extensions/wikibase/src/org/openrefine/wikibase/editing/EditBatchProcessor.java
  extensions/wikibase/src/org/openrefine/wikibase/editing/NewEntityLibrary.java
  extensions/wikibase/src/org/openrefine/wikibase/operations/PerformWikibaseEditsOperation.java
  extensions/wikibase/src/org/openrefine/wikibase/updates/MediaInfoEdit.java
  extensions/wikibase/tests/src/org/openrefine/wikibase/editing/EditBatchProcessorTest.java
  extensions/wikibase/tests/src/org/openrefine/wikibase/editing/NewEntityLibraryTest.java
  extensions/wikibase/tests/src/org/openrefine/wikibase/editing/ReconEntityRewriterTest.java
  extensions/wikibase/tests/src/org/openrefine/wikibase/operations/PerformWikibaseEditsOperationTest.java
Labels: Type: Bug, wikicommons

#6974 grel: Translate expressions after a column rename
  modules/core/src/main/java/com/google/refine/expr/Evaluable.java
  modules/grel/src/main/java/com/google/refine/grel/ast/ArrayExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/BracketedExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/ControlCallExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/FieldAccessorExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/FunctionCallExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/GrelExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/LiteralExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/OperatorCallExpr.java
  modules/grel/src/main/java/com/google/refine/grel/ast/VariableExpr.java
  modules/grel/src/test/java/com/google/refine/grel/GrelTests.java
  modules/grel/src/test/java/com/google/refine/grel/ast/ArrayExprTest.java
  modules/grel/src/test/java/com/google/refine/grel/ast/BracketedExprTest.java
  modules/grel/src/test/java/com/google/refine/grel/ast/ControlCallExprTest.java
  modules/grel/src/test/java/com/google/refine/grel/ast/ExprTestBase.java
  modules/grel/src/test/java/com/google/refine/grel/ast/FieldAccessorExprTest.java
  modules/grel/src/test/java/com/google/refine/grel/ast/FunctionCallExprTest.java
  modules/grel/src/test/java/com/google/refine/grel/ast/LiteralExprTest.java
  modules/grel/src/test/java/com/google/refine/grel/ast/OperatorCallExprTest.java
  modules/grel/src/test/java/com/google/refine/grel/ast/VariableExprTest.java
Labels: size/M

#7058 ci: Switch locale to French for Java tests
  main/src/com/google/refine/operations/recon/ReconCopyAcrossColumnsOperation.java
  main/tests/server/src/com/google/refine/operations/cell/BlankDownTests.java
  main/tests/server/src/com/google/refine/operations/cell/FillDownTests.java
  main/tests/server/src/com/google/refine/operations/cell/KeyValueColumnizeTests.java
  main/tests/server/src/com/google/refine/operations/cell/MassOperationTests.java
  main/tests/server/src/com/google/refine/operations/cell/MultiValuedCellJoinOperationTests.java
  main/tests/server/src/com/google/refine/operations/cell/MultiValuedCellSplitOperationTests.java
  main/tests/server/src/com/google/refine/operations/cell/TextTransformOperationTests.java
  main/tests/server/src/com/google/refine/operations/cell/TransposeColumnsIntoRowsOperationTest.java
  main/tests/server/src/com/google/refine/operations/cell/TransposeRowsIntoColumnsOperationTests.java
  main/tests/server/src/com/google/refine/operations/column/ColumnAdditionByFetchingURLsOperationTests.java
  main/tests/server/src/com/google/refine/operations/column/ColumnAdditionOperationTests.java
  main/tests/server/src/com/google/refine/operations/column/ColumnMoveOperationTests.java
  main/tests/server/src/com/google/refine/operations/column/ColumnRemovalOperationTests.java
  main/tests/server/src/com/google/refine/operations/column/ColumnRenameOperationTests.java
  main/tests/server/src/com/google/refine/operations/column/ColumnReorderOperationTests.java
  main/tests/server/src/com/google/refine/operations/column/ColumnSplitOperationTests.java
  main/tests/server/src/com/google/refine/operations/recon/ExtendDataOperationTests.java
  main/tests/server/src/com/google/refine/operations/recon/ReconClearSimilarCellsOperationTests.java
  main/tests/server/src/com/google/refine/operations/recon/ReconCopyAcrossColumnsOperationTests.java
  main/tests/server/src/com/google/refine/operations/recon/ReconDiscardJudgmentsOperationTests.java
  main/tests/server/src/com/google/refine/operations/recon/ReconJudgeSimilarCellsOperationTests.java
  main/tests/server/src/com/google/refine/operations/recon/ReconMarkNewTopicsOperationTests.java
  main/tests/server/src/com/google/refine/operations/recon/ReconMatchBestCandidatesOperationTests.java
  main/tests/server/src/com/google/refine/operations/recon/ReconMatchSpecificTopicOperationTests.java
  main/tests/server/src/com/google/refine/operations/recon/ReconUseValuesAsIdsOperationTests.java
  main/tests/server/src/com/google/refine/operations/row/RowAdditionOperationTests.java
  main/tests/server/src/com/google/refine/operations/row/RowFlagOperationTests.java
  main/tests/server/src/com/google/refine/operations/row/RowRemovalOperationTests.java
  main/tests/server/src/com/google/refine/operations/row/RowReorderOperationTests.java
  main/tests/server/src/com/google/refine/operations/row/RowStarOperationTests.java
  modules/grel/src/test/java/com/google/refine/expr/functions/CrossTests.java
  modules/grel/src/test/java/com/google/refine/expr/functions/arrays/ZipTests.java
  modules/grel/src/test/java/com/google/refine/expr/functions/html/InnerHtmlTests.java
  modules/grel/src/test/java/com/google/refine/expr/functions/xml/WholeTextTests.java
  modules/grel/src/test/java/com/google/refine/expr/functions/xml/XmlTextTests.java
  modules/grel/src/test/java/com/google/refine/grel/controls/ForNonBlankTests.java
  modules/grel/src/test/java/com/google/refine/grel/controls/IfTests.java
  modules/grel/src/test/java/com/google/refine/grel/controls/IsBlankTests.java
  modules/grel/src/test/java/com/google/refine/grel/controls/IsEmptyStringTests.java
  modules/grel/src/test/java/com/google/refine/grel/controls/IsErrorTests.java
  modules/grel/src/test/java/com/google/refine/grel/controls/IsNonBlankTests.java
  modules/grel/src/test/java/com/google/refine/grel/controls/IsNotNullTests.java
  modules/grel/src/test/java/com/google/refine/grel/controls/IsNullTests.java
  modules/grel/src/test/java/com/google/refine/grel/controls/IsNumericTests.java
  modules/grel/src/test/java/com/google/refine/grel/controls/WithTests.java
  pom.xml
Labels: Type: Bug, tests

#7063 test: Happy path for RenameColumnCommand
  main/tests/server/src/com/google/refine/commands/column/RenameColumnCommandTests.java
Labels: tests

#6988 facets: Add column dependency extraction
  main/tests/server/src/com/google/refine/browsing/facets/ListFacetTests.java
  main/tests/server/src/com/google/refine/browsing/facets/RangeFacetTests.java
  main/tests/server/src/com/google/refine/browsing/facets/ScatterplotFacetTests.java
  main/tests/server/src/com/google/refine/browsing/facets/TextSearchFacetTests.java
  main/tests/server/src/com/google/refine/browsing/facets/TimeRangeFacetTests.java
  modules/core/src/main/java/com/google/refine/browsing/EngineConfig.java
  modules/core/src/main/java/com/google/refine/browsing/facets/FacetConfig.java
  modules/core/src/main/java/com/google/refine/browsing/facets/ListFacet.java
  modules/core/src/main/java/com/google/refine/browsing/facets/RangeFacet.java
  modules/core/src/main/java/com/google/refine/browsing/facets/ScatterplotFacet.java
  modules/core/src/main/java/com/google/refine/browsing/facets/TextSearchFacet.java
  modules/core/src/main/java/com/google/refine/browsing/facets/TimeRangeFacet.java
  modules/core/src/test/java/com/google/refine/browsing/EngineConfigTests.java
Labels: size/L

#7077 Use all 4 cores during build test for server
  .github/workflows/pull_request_server.yml
Labels: CI/CD

#7086 Fix test-jar still being generated if -DskipTests is added
  main/pom.xml
  pom.xml
Labels: Type: Bug, maintainability, maven

#7079 fix: Deserialization of old cell splitting operation
  main/src/com/google/refine/operations/cell/MultiValuedCellSplitOperation.java
  main/tests/server/src/com/google/refine/operations/cell/MultiValuedCellSplitOperationTests.java
Labels: Type: Bug

#7090 wikibase: Fix label fetching in QA issues for new entities
  extensions/wikibase/src/org/openrefine/wikibase/qa/EditInspector.java
  extensions/wikibase/tests/src/org/openrefine/wikibase/qa/EditInspectorTest.java
Labels: Type: Bug, wikibase

#7061 fixes #7025: Keep only matching rows
  main/resources/com/google/refine/operations/OperationDescription.properties
  main/src/com/google/refine/commands/row/KeepMatchingRowsCommand.java
  main/src/com/google/refine/operations/row/RowKeepMatchedOperation.java
  main/tests/server/src/com/google/refine/operations/row/RowKeepMatchedOperationTest.java
  main/webapp/modules/core/MOD-INF/controller.js
  main/webapp/modules/core/langs/translation-en.json
  main/webapp/modules/core/scripts/views/data-table/data-table-view.js
Labels: Type: Feature Request, Status: Pending Review

#7068 Wikibase : New media upload support for validation of mandatory properties
  extensions/wikibase/module/langs/translation-en.json
  extensions/wikibase/module/scripts/commons-manifest-v2.0.js
  extensions/wikibase/module/scripts/wikibase-manifest-schema-v1.js
  extensions/wikibase/module/scripts/wikibase-manifest-schema-v2.js
  extensions/wikibase/src/org/openrefine/wikibase/manifests/Manifest.java
  extensions/wikibase/src/org/openrefine/wikibase/manifests/ManifestV1.java
  extensions/wikibase/src/org/openrefine/wikibase/manifests/ManifestV2.java
  extensions/wikibase/src/org/openrefine/wikibase/qa/scrutinizers/NewEntityScrutinizer.java
  extensions/wikibase/tests/data/manifest/commons-manifest-v2.0.json
  extensions/wikibase/tests/data/manifest/wikidata-manifest-v1.0.json
  extensions/wikibase/tests/src/org/openrefine/wikibase/qa/scrutinizers/NewEntityScrutinizerTest.java
  main/tests/cypress/cypress/e2e/extensions/wikibase/select_wikibase_instance.cy.js
Labels: Type: Feature Request, Priority: Low, Theme: UX/Usability, logic, Module: Frontend
